### ISSUE TITLE
Computercraft Error on first start

### ISSUE THREAD

**Issue by ItsDrike** [LemADEC/WarpDrive#437] opened 2020-02-20 19:05 UTC
**Describe the bug**
I have just started using this mod, so it could be an error on my side, but I don't think it is.
I was following the video tutorial on youtube linked on [curseforge](https://www.curseforge.com/minecraft/mc-mods/opencomputers). When I started the advanced computer, I got an error (described in To Reproduce section)

**To Reproduce**
(I wouldn't call this a step but I should mention it: I'm running Minecraft on a Linux machine - Ubuntu Bionic Beaver, but that shouldn't be important)
1.  Build a small platform in the overworld dimension
2.  Place Frigate Ship Core, Frigate Ship Controller, Zero-Point Module and an Advanced Computer next to each other on that platform
3.  Open the computer
4.  See error: startup:33: attempt to call field 'isInterfaced' (a nil value)

**Expected behavior**
Well, the computer should show the control program...

**Screenshots**
![Screenshot_20200220_195915](https://user-images.githubusercontent.com/20902250/74968725-96425080-541b-11ea-8db0-66e68f314a84.png)
![image](https://user-images.githubusercontent.com/20902250/74968787-b3771f00-541b-11ea-9b7e-2368400e9432.png)

**Versions** (latest is not a valid answer)
-   WarpDrive version: WarpDrive-1.12.2-1.5.12
-   Forge version: 1.12.2-forge1.12.2-14.23.5.2817
-   Modpack name/version: I'm not using any public modpack, just my set of mods.
-   Other notable mods & version: I have quite a lot of other mods so I'll just paste a  screenshot here where you can see all of them and their versions:
![image](https://user-images.githubusercontent.com/20902250/74969025-2a141c80-541c-11ea-935a-09ffb75b0c1f.png)

**Comment by LemADEC** [comment] 2020-02-20 19:44
There no "Frigate ship controller", there's only "REMOTE frigate ship controller". Read the tooltips carefully.
Also, on the screenshot, you've placed 2 "Ship cores" while your description refers to a ship core and controller.

That being said, you seem to use an older corrupted version of Pneumaticraft mod. Look for the properly updated one instead: https://www.curseforge.com/minecraft/mc-mods/pneumaticcraft-repressurized/files

Also, MalisisDoor is fairly unstable and laggy, consider removing it.

**Comment by ItsDrike** [comment] 2020-02-20 20:50
I haven't noticed, yes I put 2 ship cores, but when I use the remote controller and click on it, it says Unknown ship core signature. I have tried to shift-click on the ship core with it, but that says:
Frigate Ship Core has no signature yet! I don't really understand what should I do next and when I place a computer next to the remote controller or right next to ship core it gives the same error

**Comment by LemADEC** [comment] 2020-02-21 00:05
Remote is for remote. Make simple things work before going complicated.

You've a conflicting mod. Start by updating Pneumaticraft, if it persists, remove mods until you find the conflicting one.

**Comment by LemADEC** [comment] 2020-02-25 23:21
Any update on this?

**Comment by ItsDrike** [comment] 2020-02-29 02:56
Oh, sorry I forgot about this, I got it working, but I'd like to mention that I needed to connect the ship core to the computer using the networking cable and wired modems, it did give that error when I simply paced computer next to it

**Comment by LemADEC** [comment] 2020-02-29 10:49
I can't reproduce it, I understand its fixed on your side, hence closing

**Closed as completed by LemADEC** 2020-02-29 10:49 UTC
Labels: bug, Pending user feedback
