### ISSUE TITLE
OpenComputers GPU lost(?) after chunk reloading or jump

### ISSUE THREAD

**Issue by nosknut** [LemADEC/WarpDrive#265] opened 2017-05-25 08:47 UTC
After a jump the computer stops operating, cant b ineracted with and must be rebooted with the power button inside the commputercase

**Comment by LemADEC** [comment] 2017-05-27 08:53
Please specify which mods version are involved.
Try previous versions of OpenComputers too.
Also, specify which LUA scripts you are using for which blocks.

**Comment by nosknut** [comment] 2017-05-27 08:58
OpenComputers-1.6.2.12
WarpDrive-1.3.30
Scripts:
not anything speceal. just using the dimmension and movement "settings" ans calling jump() and after jump the  computer freezes

**Comment by Elanis** [comment] 2017-06-19 08:21
Same bug here.
OpenComputers-1.6.2.12
WarpDrive-1.3.30

We're using the basic script given with ship controller in /mnt/

**Comment by LemADEC** [comment] 2017-06-19 08:39
I heard of 2 bugs in OpenComputers:
1- display doesn't reconnect properly with OpenOS after reloading chunk or jumping
2- function pointers are lost are reloading chunk or jumping
The latest is preventing you to change pages or see it refreshing.
The only workaround I have access to is to "reset the computer after each jump".
Some players have patched their OpenOS but didn't share the fix as of now.

**Comment by nosknut** [comment] 2017-06-19 08:42
If you change the openos version to one that works during load of the mod, that should do it.

**Comment by LemADEC** [comment] 2017-06-19 08:50
Again, nobody shared the fix for it.

**Comment by nosknut** [comment] 2017-06-19 08:52
Change the openos version. Thst is the fix

**Comment by nosknut** [comment] 2017-06-19 08:56
I just did

**Comment by LemADEC** [comment] 2017-06-19 18:50
Change to what version?

**Comment by nosknut** [comment] 2017-06-19 21:43
1.5 should be fine

**Comment by LemADEC** [comment] 2017-06-19 21:53
1.5 of what the mod or the OpenOS script?

**Comment by nosknut** [comment] 2017-06-19 21:54
mod OpenComputers

**Comment by nosknut** [comment] 2017-06-19 21:55
but i am pretty shure just changing the openos version from 1.5 should fix it too

**Comment by teevik** [comment] 2017-08-10 12:26
@nosknut Is it fixed then?

**Comment by KyeDuo** [comment] 2017-08-19 22:29
ok....here is my examination of this. Breaking and replacing the screen updates it and reveals that the OC goes back to the basic OS after jumping, the program state isn't preserved. you can restart the program by running it without restarting the computer

**Comment by nosknut** [comment] 2017-08-19 22:30
dossent mean that the problem is solved

**Comment by KyeDuo** [comment] 2017-08-20 00:42
@nosknut 
just trying to help with more information

**Comment by LemADEC** [comment] 2017-08-20 05:28
As far as I know, function pointers are lost during the reloading, which prevents updating the pages or handling key strokes in the mod provided LUA scripts. It's a regression in OC 1.6.
Multiple players say they have a patch for it, nobody shared it.

**Comment by KyeDuo** [comment] 2017-08-20 17:19
@LemADEC 
once you replace the monitor the computer works fine.

**Comment by NovaLynxie** [comment] 2017-08-21 09:27
Well after a lot of searching, it finally comes to an end. The bugs mentioned by LemADEC describes what I've experienced with Opencomputers after every jump.
> I heard of 2 bugs in OpenComputers:
1- display doesn't reconnect properly with OpenOS after reloading chunk or jumping
2- function pointers are lost are reloading chunk or jumping
The latest is preventing you to change pages or see it refreshing.
The only workaround I have access to is to "reset the computer after each jump".
Some players have patched their OpenOS but didn't share the fix as of now.

Has there been any news of a fix for this yet?
Also if it's possible, where can one retrieve the older version of OpenOS, such as v1.5?

**Comment by LemADEC** [comment] 2017-08-21 14:07
You can install an older version of OpenOS 1.5, put it on a floppy, reinstall latest OC and install from that 'golden' floppy.
Or just stick to the older version of OC
Or convince them to fix the bug

**Comment by nosknut** [comment] 2017-08-21 14:49
Replacing the screen wont fix it. The computer must be rebooted.

**Comment by KyeDuo** [comment] 2017-08-21 21:05
@nosknut 
it works for me, you have to restart the program

**Comment by nosknut** [comment] 2017-08-21 21:49
Aka rebooting the computer

**Comment by nosknut** [comment] 2017-08-21 21:49
Wich can only be done manually

**Comment by KyeDuo** [comment] 2017-08-22 01:09
@nosknut 
restarting the program =/= rebooting the comp
steps:
break screen
replace screen
go to home directory if not already there
run the startup file
may be faster than rebooting the comp depending on tool

**Comment by nosknut** [comment] 2017-08-22 05:48
The point of using oc is automation and remote applications

**Comment by nosknut** [comment] 2017-08-22 05:49
If manual action is required, its no longer a remote application is it ....

**Comment by LemADEC** [comment] 2017-09-08 16:14
OC team was able to reproduce it here apparently: https://github.com/MightyPirates/OpenComputers/issues/2503

**Comment by LemADEC** [comment] 2017-09-08 16:20
Probably related with https://github.com/MightyPirates/OpenComputers/issues/2302 which provides a LUA patch

**Comment by LemADEC** [comment] 2017-09-08 16:22
@KyeDuo @nosknut can you guys confim the LUA patch fix the issue for you?

**Comment by nosknut** [comment] 2017-09-08 16:25
changing to a prevous openos makes it work again

**Comment by KyeDuo** [comment] 2017-09-09 14:19
as written, that code doesn't work to fix this problem.
and using openOS 1.5 does not work with the beta branch WD. the code will appear to run, but it crashes every time you try to access one of the programs functions.
edit: ok...further testing with servers and remote terminals allows a sort of work-around....it still gets the number keys options don't update the screen when you jump/restart world issue, but it does still work...will test out more and provide information.
edit 2: server/remote terminal doesn't need the code to behave as described.
edit 3: it seems that the ships position doesn't get updated on the screen when you use a server....I'll try to add in a manual refresh trigger for the main screen....If I can figure out how.

**Comment by LemADEC** [comment] 2017-09-09 21:00
There's already a timer to refresh the screen every few seconds, it might be bugged by OC during chunk reloading.
I wonder if there's an easy way to detect the bug from LUA, that way we could force a computer restart to recover.

**Comment by KyeDuo** [comment] 2017-09-10 14:51
the screen still refreshes, but the coords don't update.  The core cool down finished text does come up and leave in the remote terminal after a jump without rebooting.
considering it almost always bugs out after a jump, perhaps a timer tied to the jump warmup timer so that it will reload every time, after it jumps.

**Comment by LemADEC** [comment] 2017-09-11 02:23
Cooldown showing up means GPU is still accessible and events are working, somehow.
Coordinates not updating could be intended in WD LUA itself, I'll have to check.

It also gets stuck on chunkloading, hence the need to detect it.

**Comment by KyeDuo** [comment] 2017-09-14 16:36
the server working, mostly, may be because the screen and kb are virtual and something about a real one screws it up. I wonder if a pause in the program while jumping would do anything. Maybe a pause with a reconnecting the screen.

**Comment by LemADEC** [comment] 2017-10-03 21:02
OpenComputers was updated with some fixes regarding GPU handling at chunk loading. Try it out, see if it fixes that one.

**Comment by KyeDuo** [comment] 2017-10-04 21:15
it is a dev build right now. I will wait till it is a formal release.

**Comment by KyeDuo** [comment] 2017-10-23 20:58
ok, tried out the new one, didn't fix it. still locks up after jumping, even tried with the new open OS.

**Comment by LemADEC** [comment] 2017-10-23 22:15
Sadly, they've closed all tickets related to the issue. I've added comments, let's see if we need to reopen one.

**Comment by payonel** [comment] 2017-10-24 22:21
Hello all, OC dev here
I'm happy to continuing working on fixing this issue, I just need a new ticket with some ambiguities **clearly** resolved. There have been numerous bugs that sound similar but were actually due to different issues. I have a list of some of the things I need clarified in my last comment this OC issue: https://github.com/MightyPirates/OpenComputers/issues/2503#issuecomment-339150077

Thanks!

**Comment by LemADEC** [comment] 2017-10-25 00:44
new issue have been created here: https://github.com/MightyPirates/OpenComputers/issues/2598

**Comment by LemADEC** [comment] 2018-02-21 23:59
Issue has been confirmed in an OC dependency here: fnuecke/eris#29
Now that we understand better what's going on, I should be able to add a workaround for it.

**Comment by payonel** [comment] 2018-02-22 01:21
@LemADEC 
> As far as I know, function pointers are lost during the reloading

I just want to point out (as I did in the OC and eris bug reports) that it isn't the function pointers, but instead the upvalue reference to a local variable shared between global and local functions - which isn't a good choice, but also probably unintentional
I would consider the `selectPage` function improperly (implicitly) declared global, and should be local -- which also saves you from this bug

**Comment by LemADEC** [comment] 2018-02-22 01:55
selectPage was initially local but wouldn't always work, forgot to comment on why it's global.
I'll have to redo some test, and remove that ugly hack.

**Closed as completed** 2018-05-08 11:16 UTC
Labels: help wanted, not a WarpDrive issue
