### ISSUE TITLE
Crash at boot with ThaumicAugmentation?

### ISSUE THREAD

**Issue by Routhinator** [LemADEC/WarpDrive#416] opened 2019-12-09 17:03 UTC
**Describe the bug**
Class not found error with Forge 14.23.5.2847 - which is the latest for 1.12.2. Normally the goto here is to update forge, but not an option.

This only happens on the server, and not the client. Might be that i have a config on the server that shouldn't be there.

**Logs**

```
2019-12-09 16:45:17,898 : INFO : net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from WarpDrive (warpdrive)
2019-12-09 16:45:17,898 : INFO : 
2019-12-09 16:45:17,898 : INFO : Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/multiplayer/WorldClient
2019-12-09 16:45:17,898 : INFO : 	at thecodex6824.thaumicaugmentation.init.CapabilityHandler.onAttachCapabilitiesChunk(CapabilityHandler.java:90) ~[CapabilityHandler.class:?]
2019-12-09 16:45:17,899 : INFO : 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_845_CapabilityHandler_onAttachCapabilitiesChunk_AttachCapabilitiesEvent.invoke(.dynamic) ~[?:?]
2019-12-09 16:45:17,899 : INFO : 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
2019-12-09 16:45:17,899 : INFO : 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
2019-12-09 16:45:17,899 : INFO : 	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:691) ~[ForgeEventFactory.class:?]
2019-12-09 16:45:17,899 : INFO : 	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:685) ~[ForgeEventFactory.class:?]
2019-12-09 16:45:17,899 : INFO : 	at net.minecraft.world.chunk.Chunk.<init>(Chunk.java:94) ~[axw.class:?]
2019-12-09 16:45:17,899 : INFO : 	at cr0s.warpdrive.world.FakeChunk.<init>(FakeChunk.java:23) ~[FakeChunk.class:?]
2019-12-09 16:45:17,899 : INFO : 	at cr0s.warpdrive.world.FakeWorld.func_72964_e(FakeWorld.java:50) ~[FakeWorld.class:?]
2019-12-09 16:45:17,899 : INFO : 	at net.minecraft.world.World.func_175726_f(World.java:305) ~[amu.class:?]
2019-12-09 16:45:17,899 : INFO : 	at net.minecraft.world.World.func_180501_a(World.java:330) ~[amu.class:?]
2019-12-09 16:45:17,900 : INFO : 	at com.rwtema.extrautils2.blocks.BlockCompressed.func_176195_g(BlockCompressed.java:115) ~[BlockCompressed.class:?]
2019-12-09 16:45:17,900 : INFO : 	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185887_b(BlockStateContainer.java:403) ~[awu$a.class:?]
2019-12-09 16:45:17,900 : INFO : 	at cr0s.warpdrive.config.Dictionary.adjustHardnessAndResistance(Dictionary.java:652) ~[Dictionary.class:?]
2019-12-09 16:45:17,900 : INFO : 	at cr0s.warpdrive.config.Dictionary.apply(Dictionary.java:589) ~[Dictionary.class:?]
2019-12-09 16:45:17,900 : INFO : 	at cr0s.warpdrive.config.WarpDriveConfig.onFMLPostInitialization(WarpDriveConfig.java:1653) ~[WarpDriveConfig.class:?]
2019-12-09 16:45:17,900 : INFO : 	at cr0s.warpdrive.WarpDrive.onFMLPostInitialization(WarpDrive.java:633) ~[WarpDrive.class:?]
2019-12-09 16:45:17,900 : INFO : 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
2019-12-09 16:45:17,900 : INFO : 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
2019-12-09 16:45:17,900 : INFO : 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
2019-12-09 16:45:17,900 : INFO : 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
2019-12-09 16:45:17,901 : INFO : 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) ~[forge-1.12.2-14.23.5.2847-universal.jar:?]
2019-12-09 16:45:17,901 : INFO : 	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) ~[?:?]
2019-12-09 16:45:17,901 : INFO : 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
2019-12-09 16:45:17,901 : INFO : 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
2019-12-09 16:45:17,901 : INFO : 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
2019-12-09 16:45:17,901 : INFO : 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
2019-12-09 16:45:17,901 : INFO : 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
2019-12-09 16:45:17,901 : INFO : 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
2019-12-09 16:45:17,901 : INFO : 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
2019-12-09 16:45:17,901 : INFO : 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
2019-12-09 16:45:17,901 : INFO : 	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
2019-12-09 16:45:17,902 : INFO : 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) ~[forge-1.12.2-14.23.5.2847-universal.jar:?]
2019-12-09 16:45:17,902 : INFO : 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) ~[forge-1.12.2-14.23.5.2847-universal.jar:?]
2019-12-09 16:45:17,902 : INFO : 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
2019-12-09 16:45:17,902 : INFO : 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
2019-12-09 16:45:17,902 : INFO : 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
2019-12-09 16:45:17,902 : INFO : 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
2019-12-09 16:45:17,902 : INFO : 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
2019-12-09 16:45:17,902 : INFO : 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
2019-12-09 16:45:17,902 : INFO : 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
2019-12-09 16:45:17,902 : INFO : 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
2019-12-09 16:45:17,902 : INFO : 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
2019-12-09 16:45:17,902 : INFO : 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
2019-12-09 16:45:17,902 : INFO : 	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
2019-12-09 16:45:17,902 : INFO : 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) ~[LoadController.class:?]
2019-12-09 16:45:17,903 : INFO : 	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:754) ~[Loader.class:?]
2019-12-09 16:45:17,903 : INFO : 	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108) ~[FMLServerHandler.class:?]
2019-12-09 16:45:17,903 : INFO : 	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338) ~[FMLCommonHandler.class:?]
2019-12-09 16:45:17,903 : INFO : 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219) ~[nz.class:?]
2019-12-09 16:45:17,903 : INFO : 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
2019-12-09 16:45:17,903 : INFO : 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
2019-12-09 16:45:17,903 : INFO : Caused by: java.lang.ClassNotFoundException: net.minecraft.client.multiplayer.WorldClient
2019-12-09 16:45:17,903 : INFO : 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
2019-12-09 16:45:17,903 : INFO : 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_222]
2019-12-09 16:45:17,903 : INFO : 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_222]
2019-12-09 16:45:17,903 : INFO : 	at thecodex6824.thaumicaugmentation.init.CapabilityHandler.onAttachCapabilitiesChunk(CapabilityHandler.java:90) ~[CapabilityHandler.class:?]
2019-12-09 16:45:17,903 : INFO : 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_845_CapabilityHandler_onAttachCapabilitiesChunk_AttachCapabilitiesEvent.invoke(.dynamic) ~[?:?]
2019-12-09 16:45:17,903 : INFO : 	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
2019-12-09 16:45:17,903 : INFO : 	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
2019-12-09 16:45:17,904 : INFO : 	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:691) ~[ForgeEventFactory.class:?]
2019-12-09 16:45:17,904 : INFO : 	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:685) ~[ForgeEventFactory.class:?]
2019-12-09 16:45:17,904 : INFO : 	at net.minecraft.world.chunk.Chunk.<init>(Chunk.java:94) ~[axw.class:?]
2019-12-09 16:45:17,904 : INFO : 	at cr0s.warpdrive.world.FakeChunk.<init>(FakeChunk.java:23) ~[FakeChunk.class:?]
2019-12-09 16:45:17,904 : INFO : 	at cr0s.warpdrive.world.FakeWorld.func_72964_e(FakeWorld.java:50) ~[FakeWorld.class:?]
2019-12-09 16:45:17,904 : INFO : 	at net.minecraft.world.World.func_175726_f(World.java:305) ~[amu.class:?]
2019-12-09 16:45:17,904 : INFO : 	at net.minecraft.world.World.func_180501_a(World.java:330) ~[amu.class:?]
2019-12-09 16:45:17,904 : INFO : 	at com.rwtema.extrautils2.blocks.BlockCompressed.func_176195_g(BlockCompressed.java:115) ~[BlockCompressed.class:?]
2019-12-09 16:45:17,904 : INFO : 	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185887_b(BlockStateContainer.java:403) ~[awu$a.class:?]
2019-12-09 16:45:17,904 : INFO : 	at cr0s.warpdrive.config.Dictionary.adjustHardnessAndResistance(Dictionary.java:652) ~[Dictionary.class:?]
2019-12-09 16:45:17,905 : INFO : 	at cr0s.warpdrive.config.Dictionary.apply(Dictionary.java:589) ~[Dictionary.class:?]
2019-12-09 16:45:17,905 : INFO : 	at cr0s.warpdrive.config.WarpDriveConfig.onFMLPostInitialization(WarpDriveConfig.java:1653) ~[WarpDriveConfig.class:?]
2019-12-09 16:45:17,905 : INFO : 	at cr0s.warpdrive.WarpDrive.onFMLPostInitialization(WarpDrive.java:633) ~[WarpDrive.class:?]
2019-12-09 16:45:17,905 : INFO : 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
2019-12-09 16:45:17,905 : INFO : 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
2019-12-09 16:45:17,905 : INFO : 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
2019-12-09 16:45:17,905 : INFO : 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
2019-12-09 16:45:17,905 : INFO : 	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) ~[forge-1.12.2-14.23.5.2847-universal.jar:?]
2019-12-09 16:45:17,905 : INFO : 	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) ~[?:?]
2019-12-09 16:45:17,905 : INFO : 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
2019-12-09 16:45:17,905 : INFO : 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
2019-12-09 16:45:17,905 : INFO : 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
2019-12-09 16:45:17,905 : INFO : 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
2019-12-09 16:45:17,905 : INFO : 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
2019-12-09 16:45:17,905 : INFO : 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
2019-12-09 16:45:17,905 : INFO : 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
2019-12-09 16:45:17,906 : INFO : 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
2019-12-09 16:45:17,906 : INFO : 	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
2019-12-09 16:45:17,906 : INFO : 	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) ~[forge-1.12.2-14.23.5.2847-universal.jar:?]
2019-12-09 16:45:17,906 : INFO : 	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) ~[forge-1.12.2-14.23.5.2847-universal.jar:?]
2019-12-09 16:45:17,906 : INFO : 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]
2019-12-09 16:45:17,906 : INFO : 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]
2019-12-09 16:45:17,906 : INFO : 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]
2019-12-09 16:45:17,906 : INFO : 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]
2019-12-09 16:45:17,906 : INFO : 	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
2019-12-09 16:45:17,906 : INFO : 	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
2019-12-09 16:45:17,906 : INFO : 	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
2019-12-09 16:45:17,906 : INFO : 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
2019-12-09 16:45:17,906 : INFO : 	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
2019-12-09 16:45:17,906 : INFO : 	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
2019-12-09 16:45:17,906 : INFO : 	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
2019-12-09 16:45:17,906 : INFO : 	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) ~[LoadController.class:?]
2019-12-09 16:45:17,907 : INFO : 	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:754) ~[Loader.class:?]
2019-12-09 16:45:17,907 : INFO : 	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:108) ~[FMLServerHandler.class:?]
2019-12-09 16:45:17,907 : INFO : 	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:338) ~[FMLCommonHandler.class:?]
2019-12-09 16:45:17,907 : INFO : 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219) ~[nz.class:?]
2019-12-09 16:45:17,907 : INFO : 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) ~[MinecraftServer.class:?]
2019-12-09 16:45:17,907 : INFO : 	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_222]
```

**Versions** (latest is not a valid answer)
 - WarpDrive version: 1.5.11
 - Forge version: 14.23.5.2847
 - Modpack name/version: Custom
 - Other notable mods & version: 

GalacticraftCore 4.0.2.238
Galacticraft-Planets 4.0.2.238
GalaxySpace 2.0.10
ExtraPlanets 0.6.0
**Additional context**

**Comment by Routhinator** [comment] 2019-12-09 17:54
Tried removing Galaxyspace just in case, no luck.

**Comment by LemADEC** [comment] 2019-12-09 18:50
ExtraUtilities and ThaumicAugmentation are involved, please include their versions here.
You can disable WardFocus in ThaumicAugmentation to work around this.

**Comment by Routhinator** [comment] 2019-12-09 19:00
ExtraUtilities - 1.9.9
ThaumicAugmentation - 1.1.13

Trying your suggested workaround.

**Comment by Routhinator** [comment] 2019-12-09 19:19
@LemADEC your workaround got me past this crash. Seems like it's ThaumicAugmentation. I'll open a bug over there?

**Comment by LemADEC** [comment] 2019-12-09 19:47
I can't reproduce in dev with latest version so it's probably already covered by another fix that will be in next update.
There's no need for a ticket on their side, just remember to re-enable WardFocus once you update WarpDrive.

**Closed as completed by LemADEC** 2019-12-09 19:47 UTC
Labels: bug

**Comment by Routhinator** [comment] 2019-12-09 20:06
Thanks for your assistance.
