### ISSUE TITLE
Extremely slow LAN/Local server is not supported

### ISSUE THREAD

**Issue by MysticalLlama** [LemADEC/WarpDrive#194] opened 2016-07-25 22:54 UTC
When I jump up to space, I am teleported there, but my spaceship is not. The blocks still are kind of present, but they are not visible and when I run into one, I am teleported back. When I place blocks the same thing occurs. The blocks are not really there. No asteroids can be found either. I'm playing on a 1.7.10 forge server.

**Comment by LemADEC** [comment] 2016-07-26 01:13
We need a the full logs with all options enabled.
What blocks are used to build your ship?
What version of the mod are you using?

**Comment by MysticalLlama** [comment] 2016-07-26 01:27
```
[19:24:10] [Server thread/INFO] [WarpDrive]: TileEntityShipCore '20gggg' @ 'world' (306 122 -152) messageToAllPlayersOnShip: Running pre-jump checklist...
[19:24:20] [Server thread/INFO] [WarpDrive]: Profiling StarMapRegistry cleanup: 0.055 ms
[19:24:20] [Server thread/INFO] [WarpDrive]: TileEntityShipCore '20gggg' @ 'world' (306 122 -152) Performing basic jump of 474 blocks inside (293, 117, -158) to (319, 128, -146) with an actual mass of 474 blocks toward direction 666 over 1 blocks.
[19:24:20] [Server thread/INFO] [WarpDrive]: Profiling Jump.chunkLoading: 8.955 ms
[19:24:20] [Server thread/INFO] [WarpDrive]: Profiling Jump.saving: 9.997 ms
[19:24:20] [Server thread/INFO] [WarpDrive]: Profiling Jump.borders: 0.742 ms
[19:24:20] [Server thread/INFO] [WarpDrive]: Profiling Jump.forceTargetChunks: 0.356 ms
[19:24:20] [Server thread/INFO] [WarpDrive]: JumpShip/302218025 '2488b101-d69b-4964-a102-bfe175c904b9:20gggg' @ 'world' (306 122 -152) messageToAllPlayersOnShip: Jumping of 0 blocks (0 0 0)
[19:24:20] [Server thread/INFO] [WarpDrive]: Profiling Jump.transformer: 12.699 ms, total: 13.055 ms
[19:24:20] [Server thread/INFO] [WarpDrive]: Profiling Jump.moveBlocks: 26.542 ms
[19:24:20] [Server thread/INFO] [WarpDrive]: Profiling Jump.moveExternals: 0.285 ms
[19:24:21] [Server thread/WARN] [WarpDrive]: Object already has a weight defined, skipping Filler(tile.stone@0) with weight 1
[19:24:21] [Server thread/WARN] [WarpDrive]: Object already has a weight defined, skipping Filler(tile.stone@0) with weight 5
[19:24:21] [Server thread/WARN] [WarpDrive]: Object already has a weight defined, skipping Filler(tile.stonebrick@0) with weight 1
[19:24:21] [Server thread/WARN] [WarpDrive]: Object already has a weight defined, skipping Filler(tile.stone@0) with weight 5
[19:24:21] [Server thread/WARN] [WarpDrive]: Object already has a weight defined, skipping Filler(tile.stonebrick@0) with weight 1
[19:24:21] [Server thread/INFO] [WarpDrive]: Profiling [AsteroidInstance] Generating MetaOrb ClusteredAsteroid of 1 cores with radius of 4: 2.766 ms
[19:24:21] [Server thread/ERROR] [WarpDrive]: Patched IC2 API, new instance is 'ic2.core.network.NetworkManager@6c6d7df4'
[19:24:21] [Server thread/INFO] [WarpDrive]: Profiling Jump.removeBlocks: 16.982 ms
[19:24:21] [Server thread/INFO] [WarpDrive]: Profiling Jump.chunkUnloading: 2.178 ms
[19:24:21] [Server thread/INFO] [WarpDrive]: Profiling Jump.finishing(): 1.374 ms
```

I was just using one of the /generate ship ships.
I am using version 1.7.10-1.3.22

**Comment by LemADEC** [comment] 2016-07-26 08:17
We need ALL logging options to be enabled.
We need ALL logs starting from the boot of the server.
Does the ship appears if you disconnect and reconnect? if you press F3+A ?

**Comment by MysticalLlama** [comment] 2016-07-26 17:10
The ship doesn't appear when I reconnect or press f3+A. There are not any blocks in space, anywhere. When I jump into space it says jumping 0 blocks, then I appear there. 

Logs: https://docs.google.com/document/d/1AdZPirHS2biBSsz3FyYua0PzYTPrAl5EMUCpU0OLSZs/edit?usp=sharing

**Comment by LemADEC** [comment] 2016-07-26 21:36
What are those 2 mods PeegProPlus and WarpDimensions? can you try without them?

You server is transferring about 50 times slower than a dedicated box, that can't be good either. Try reducing blocks_per_tick to 100 in the WarpDrive.cfg configuration file, general section.

**Comment by MysticalLlama** [comment] 2016-07-26 22:25
I tried removing those mods and reducing the blocks_per_tick to 100, but the problem still occured :( 

Logs: 
https://docs.google.com/document/d/1C67-kvL9t0pFNYpqO4F7_6x3olmDvJfhdLnawEkb7RY/edit?usp=sharing

**Comment by LemADEC** [comment] 2016-07-27 08:10
Try removing WorldBorder and WorldEdit.
Try jumping a 4x4 chunks plateform of cobblestone and see if all or only some parts of it are lost.

While in space, try "/generate moon" and see if anything shows up, reconnect and confirm it something shows or disappeared (note: you'll be inside the moon).

Finally, try with the attached "Slow motion" version of the mod.
[WarpDrive-1.7.10-1.3.25-slowMotion.-.zip](https://github.com/LemADEC/WarpDrive/files/385583/WarpDrive-1.7.10-1.3.25-slowMotion.-.zip)

**Comment by MysticalLlama** [comment] 2016-07-27 19:31
I tried all of your ideas but blocks still don't appear in space. All of the blocks on the cobble platform disappeared and the /generate moon seemed to just teleport me down 20 blocks.

**Comment by LemADEC** [comment] 2016-07-27 19:55
Including with the modified mod I've posted?

**Comment by MysticalLlama** [comment] 2016-07-27 22:02
Yeah... :(

**Comment by LemADEC** [comment] 2016-07-27 22:17
Looks like a vanilla bug due to your server being too slow, not much I can do on my side

**Comment by LemADEC** [comment] 2016-07-30 12:35
Are you running in dedicated mode or opening your local game ?

**Comment by MysticalLlama** [comment] 2016-07-30 19:08
Local game.

**Comment by LemADEC** [comment] 2018-02-04 11:37
Blocks placement and air generators were largely improved in 1.3.35+. Open a new ticket with fresh logs if the issue is still reproduced

**Closed as completed by LemADEC** 2018-02-04 11:37 UTC
Labels: low Priority
