### ISSUE TITLE
Configurable minimum Y distance on planets

### ISSUE THREAD

**Issue by StargateMC** [LemADEC/WarpDrive#159] opened 2016-04-22 22:44 UTC
Just a quick Feature request for a config option - It would be really great if we could define a minimum Y value for warpdrive ships to function at on planets.

Would allow players to be safe from people warping into their bases because the core would not allow it if their base was below (for example?) Y150

**Comment by LemADEC** [comment] 2016-04-22 23:27
Your ship needs to land which is typically around 64.
Many players hide their ship in their underground base too.

To be actually able to jump into a base, there's should be no collision with any blocks. If you miss, you'll get a pretty big explosion.

I'm more inclined to add a minimum ship size constrains for ship, so it's harder to jump into base without colliding...

**Comment by StargateMC** [comment] 2016-04-22 23:28
But if you have grief prevention or similar installed, this just bypasses all of that completely... trashing the other persons base.
No worries :) I might just add a custom config for my server somehow. 

Just trying to make this not be able to bypass our protections - even if that means people need to create an elevated dock and cant hide their ship.

Solution might be actually integrating with those plugins, so you have a 'whitelist' of regions you can land in (i.e only a place with no region, or a region the player owns).... would you be open to supporting that if I put the code together? (I already handle integrating with grief prevention style plugins with https://www.spigotmc.org/threads/regenerator-paid.140843/)

**Comment by LemADEC** [comment] 2016-04-23 05:26
Protection plugins aren't supported yet, I forgot to put a ticket for it. The issue is to identify which crew member to use for the jump check, like if you hijack the admin ship, or an Admin is aboard, you could bypass everything...

**Comment by StargateMC** [comment] 2016-05-08 01:06
@LemADEC How do I obtain the person who hit jump?

It would be up to the admins to prevent hijacking of their vessels I would imagine (You can prevent a player using a computer in your 'safezone' in the first place for example).

Ive even made a plugin that does that for Factions users - https://www.spigotmc.org/resources/perimeter.22469/

I'm going to try replicating how you're supporting different mods to support Factions to start. If I succeed, I'll let you know :P

**Comment by LemADEC** [comment] 2016-05-08 05:48
Your approach is very specific to factions which is based on Bukkit. The latest is dead for forge mods on 1.8+, so I would work on a more sustainable approach which is to use forge event systems.
The current issue is that WarpDrive break and place blocks without asking for perms to other mods. It's a bit tedious (and slow) to do, but it's generic and remains valid for 1.8+. The hard part is to identify the ship pilot player.

**Comment by StargateMC** [comment] 2016-05-08 05:57
@LemADEC What mods support grief prevention at all in forge full stop, let alone 1.8?
99% of protection plugins/mods (that are worth using) are bukkit based... and run on Thermos/KCauldron.
The alternatives will become available for sponge on 1.9.

The alternative would be to use break/place events, and if any of them are cancelled, prevent the warp?
You'd have to use a fakeplayer and still know who the player is though.

If you created a generic compat class that supported canWarpInto() and canWarpOutOf(), I could do the bukkit support. It doesn't have to be factions - I'd create a separate class for each plugin.

**Comment by LemADEC** [comment] 2016-05-08 13:06
Forge supports it natively since at least 1.6.4. It's just not advertised properly so mod authors don't implement it. Consequently, forge based protection mods have to patch other mods to fully implement their protection.
Yes, break/place event are the ones I'm talking about. Implementing those would automatically supports all plugins and mods.

**Comment by LemADEC** [comment] 2016-07-23 03:36
Plugin protection is already implemented, hence closing

**Closed as completed by LemADEC** 2016-07-23 03:36 UTC
