### ISSUE TITLE
Useless energy draining

### ISSUE THREAD

**Issue by ZLOFENIX** [LemADEC/WarpDrive#184] opened 2016-06-10 22:05 UTC
https://github.com/LemADEC/WarpDrive/blob/MC1.7/src/main/java/cr0s/warpdrive/block/TileEntityAbstractLaser.java#L110
Do:
if (count == 0 || totalEnergy < amount) {

**Comment by LemADEC** [comment] 2016-06-11 00:35
This was the intended behavior when I've implemented it.

**Comment by ZLOFENIX** [comment] 2016-06-11 12:32
Drain energy to nothing? Why?
I tried laser miner on earth with silk touch, even 16k eu/t was not enough to power it.

**Comment by LemADEC** [comment] 2016-06-11 18:52
It's the same principle with RF API: if you request more energy than available, everything gets consumed and the caller have to deal with what was available.

I've only tested silk touch mining with MFSU, which is way below 16k EU/t. Is it not mining at all?

**Comment by ZLOFENIX** [comment] 2016-06-11 20:13
But in which mod this shit? Thermal, ic2, mekanism - all will not drain energy to nothing, just will not work, until they can. What i suggested - same thing, miner will wait some energy, use it, then again wait for more.

Its mines 1-5 blocks and dies with useless draining, because cant fill condensator.

**Comment by LemADEC** [comment] 2016-06-11 20:22
I'm not saying there's no bug. I'm saying the bug isn't at that location.

**Comment by ZLOFENIX** [comment] 2016-06-11 20:23
Its just simpliest fix of this.

**Comment by LemADEC** [comment] 2016-06-11 20:42
I did a quick check and I see 2 issues:
- [ ] average EU/t consumption is higher than expected (about 1.5kEU/t in overworld with default setup) 
- [ ] cooldown isn't working. Normally, it case of 'low power', the mining laser is put on hold for a few seconds so the Energy production catch up and we don't lag the server

I'll dig further once I'm done with the force field.

**Comment by LemADEC** [comment] 2016-07-25 21:52
Cooldowns and energy drain are fixed in 1.3.26.

**Closed as completed by LemADEC** 2016-07-25 21:52 UTC
