### ISSUE TITLE
[regression] ImmersiveEngineering multiblocks duplicating during jump

### ISSUE THREAD

**Issue by netherever** [LemADEC/WarpDrive#459] opened 2020-06-17 07:28 UTC
**Describe the bug**
After jump remain (as item) next blocks:
Immersive engineering: connectors, aluminium post, multiblock fluid tank (iron sheetmetal) (maybe every multiblock, checked only this)
Nuclearcraft: multiblock fussion core
Also IE fluid pipe after jump sometime visual disconected (but remain in working state)

**To Reproduce**
Just warp mentioned structures.

**Expected behavior**
Destroying multiblock right (without dupe items)

**Screenshots**
![2020-06-18_03 02 44](https://user-images.githubusercontent.com/57923005/84950633-65e49780-b119-11ea-8e06-c9d10edc4557.png)

![2020-06-18_03 02 46](https://user-images.githubusercontent.com/57923005/84950642-6bda7880-b119-11ea-960f-47d3c6908e6e.png)

![2020-06-18_03 02 47](https://user-images.githubusercontent.com/57923005/84950657-739a1d00-b119-11ea-834b-03bd640d590e.png)

**Logs**
https://pastebin.com/pqqwj0gE

**Versions**
WarpDrive version: 1.5.13
Forge version: 14.23.5.2854
Other mod 
BetterFps-1.4.8.jar
BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar
CodeChickenLib-1.12.2-3.2.3.358-universal.jar
CraftTweaker2-1.12-4.1.20.570.jar
GeographiCraft-1.12-0.8.9b.jar
ImmersiveEngineering-0.12-92.jar
jei_1.12.2-4.15.0.293.jar
justenoughdimensions-1.12.2-1.6.0-dev.20200416.184714.jar
lostcities-1.12-2.0.22.jar
ModularPowersuits-1.12.2-1.0.46.jar
MrTJPCore-1.12.2-2.1.4.43-universal.jar
NuclearCraft-2.18t-1.12.2.jar
Numina-1.12.2-1.0.38.jar
OpenComputers-MC1.12.2-1.7.5.192.jar
RTG-1.12.2-6.1.0.0-snapshot.1.jar
tlskincape_1.12.2-1.4.jar

**Comment by LemADEC** [comment] 2020-06-17 20:10
Last is NOT a version number.
Your Forge version not updated.
Logs are missing, remember to enable them all.
We need a picture of your setup, and the related ship schematic.
Issue isn't reproduced, you didn't follow the form.

**Comment by netherever** [comment] 2020-06-17 21:15
> Your Forge version not updated.

Then tell what version must be.

**Comment by netherever** [comment] 2020-06-17 22:47
https://pastebin.com/4deNCB49
https://gist.github.com/netherever/220f6460b76d82875b9b84fa5959fca8
B:enable_jumpblocks_logs=true

**Comment by netherever** [comment] 2020-06-18 01:32
CodeChickenLib-1.12.2-3.2.3.358-universal.jar
ImmersiveEngineering-0.12-92.jar
jei_1.12.2-4.15.0.293.jar
OpenComputers-MC1.12.2-1.7.5.192.jar
WarpDrive-1.12.2-1.5.13.jar

same with only this mods

**Comment by LemADEC** [comment] 2020-06-22 01:06
FluidTank, CokeOven & AlloySmelter are dropping as item during removal step.
MetalPress & Crusher are not reproducing the issue.
This is a regression since last update of ImmersiveEngineering compatibility module on 2018-12-14.
ImmersiveTech and ImmersivePetroleum are potentially affected too.
Version used at that time was probably ImmersiveEngineering-0.12-86 and WarpDrive dev anterior to 1.5.0. Official WarpDrive 1.5.0 does reproduce the issue, so it's probably a regression in WarpDrive.

**Comment by netherever** [comment] 2020-06-23 16:09
1) Disregard about fluid pipe - IE bug
2) Also dropping aluminum post - always, connectors (not relays) - sometimes (may be position/orientation related)

**Comment by LemADEC** [comment] 2020-06-23 21:03
All posts, along with FluidTank, CokeOven & AlloySmelter are also dropping items when broken in creative. This is an ImmersiveEngineering bug, it's probably related to the regression here.
The antidup runs too soon and fails to catch the item drops, so that should be an easy fix.
Connectors aren't dropping for me, so you'll have to be more specific on your setup.

**Comment by LemADEC** [comment] 2020-06-24 00:03
Fixed in dev

**Closed as completed by LemADEC** 2020-06-24 00:03 UTC
Labels: bug

**Comment by netherever** [comment] 2020-06-26 10:31
1)
![изображение](https://user-images.githubusercontent.com/57923005/85847973-9344db80-b7d2-11ea-82eb-757cea4876b8.png)
![изображение](https://user-images.githubusercontent.com/57923005/85848007-9fc93400-b7d2-11ea-8976-c6c6ceac27a4.png)
![изображение](https://user-images.githubusercontent.com/57923005/85848028-a788d880-b7d2-11ea-9170-1e027bc4678e.png)

2) NuclearCraft-2.18t-1.12.2.jar - fussion core (multi 3x3x3) drop/dup

**Comment by netherever** [comment] 2020-06-27 12:58
Reporting: items still dropped - but dissapear in a tick. So, sort of fixed.
But dup blocks remain - as linked connector at previous screen.
![изображение](https://user-images.githubusercontent.com/57923005/85923065-299bfe80-b8b2-11ea-8f94-dc2a55cd766b.png)

**Comment by LemADEC** [comment] 2020-06-28 12:58
still not reproduced, we'll need you full modpack configuration, saves, mods, etc.
