### ISSUE TITLE
Enan reactors - Opencomputers problems

### ISSUE THREAD

**Issue by gggddd1** [LemADEC/WarpDrive#140] opened 2016-03-02 16:40 UTC
1. Enan reactor can't be started with OC methods. You can start it, but it will not output energy and not overheating untill you'll call any method from CC. You need to add "hold = false" to OC methods similar to CC.
   ![14553778539410](https://cloud.githubusercontent.com/assets/17597973/13467139/a6e5c0c2-e0be-11e5-9976-c00b3fabb071.jpg)
2. Tonnes of errors in server console when you connecting enan reactor parts to OpenComputer and turning it on. "Trying to push signal with an unsupported argument of type ..."

**Comment by LemADEC** [comment] 2016-03-02 19:51
Please post a screenshot of your reactor setup.

**Comment by gggddd1** [comment] 2016-03-03 02:56
Just connect it to opencomputer with network card and turn computer on. You don't need to call any methods for errors happening.
![2016-03-03_07 55 19](https://cloud.githubusercontent.com/assets/17597973/13483348/53d296d8-e115-11e5-8f96-f89b853927ce.png)

[07:54:40] [Server thread/WARN]: Trying to push signal with an unsupported argument of type [Ljava.lang.Object;
[07:54:40] [Server thread/WARN]: Trying to push signal with an unsupported argument of type [Ljava.lang.Object;
[07:54:40] [Server thread/WARN]: Trying to push signal with an unsupported argument of type [Ljava.lang.Object;
[07:54:40] [Server thread/WARN]: Trying to push signal with an unsupported argument of type [Ljava.lang.Object;
[07:54:41] [Server thread/WARN]: Trying to push signal with an unsupported argument of type [Ljava.lang.Object;
[07:54:41] [Server thread/WARN]: Trying to push signal with an unsupported argument of type [Ljava.lang.Object;
[07:54:41] [Server thread/WARN]: Trying to push signal with an unsupported argument of type [Ljava.lang.Object;
[07:54:41] [Server thread/WARN]: Trying to push signal with an unsupported argument of type [Ljava.lang.Object;
[07:54:42] [Server thread/WARN]: Trying to push signal with an unsupported argument of type [Ljava.lang.Object;
[07:54:42] [Server thread/WARN]: Trying to push signal with an unsupported argument of type [Ljava.lang.Object;
[07:54:42] [Server thread/WARN]: Trying to push signal with an unsupported argument of type [Ljava.lang.Object;
[07:54:42] [Server thread/WARN]: Trying to push signal with an unsupported argument of type [Ljava.lang.Object;
[07:54:43] [Server thread/WARN]: Trying to push signal with an unsupported argument of type [Ljava.lang.Object;
[07:54:43] [Server thread/WARN]: Trying to push signal with an unsupported argument of type [Ljava.lang.Object;
[07:54:43] [Server thread/WARN]: Trying to push signal with an unsupported argument of type [Ljava.lang.Object;
[07:54:43] [Server thread/WARN]: Trying to push signal with an unsupported argument of type [Ljava.lang.Object;
[07:54:44] [Server thread/WARN]: Trying to push signal with an unsupported argument of type [Ljava.lang.Object;
[07:54:44] [Server thread/WARN]: Trying to push signal with an unsupported argument of type [Ljava.lang.Object;
[07:54:44] [Server thread/WARN]: Trying to push signal with an unsupported argument of type [Ljava.lang.Object;
[07:54:44] [Server thread/WARN]: Trying to push signal with an unsupported argument of type [Ljava.lang.Object;

**Comment by LemADEC** [comment] 2016-03-03 09:45
Looks like we have a regression here, will have to check.
For the record, you don't need the network card, it's a straight connection.
Reactor is permanently 'hold' with OC because the LUA script is too slow to maintain it due to screen refresh; I'm not quite sure how to fix that one yet.

**Comment by LemADEC** [comment] 2016-03-16 22:30
This is fixed in dev. OC GPU is quite slow compared to CC, so it's a bit harder to push the reactor to its limits.

**Closed as completed** 2016-03-17 01:27 UTC
Labels: bug
