### ISSUE TITLE
Stargates should be closed during pre-jump sequence

### ISSUE THREAD

**Issue by StargateMC** [LemADEC/WarpDrive#139] opened 2016-03-01 12:12 UTC
For Proper SGCraft compatibility, the following needs to be done;
- Stargates must be de-formed before jumping and form afterward. (Or the ring / chevron blocks need to actually be copied properly).
- Stargates must not be active while warping.

**Comment by StargateMC** [comment] 2016-03-01 13:04
https://github.com/StargateMC/WarpDrive/commit/72287286db3366e93b92bcbfc012bbcb51b69a09
https://github.com/StargateMC/WarpDrive/commit/25cb6dfe0c3dac29c213106a56cefa8ad25481d9

I think ive got it right.... not sure how to  make the dependency not a hard one though.

Config changes (these might need to be added by default):
https://github.com/StargateMC/Server/commit/52f4955b105f10e7f89f2c9d03f5845ae42c4275

**Comment by LemADEC** [comment] 2016-03-01 19:14
Try to stay focus on a single subject and finish it before moving to something else, please...

It seems you've found where to interrogate the stargate, but it's not the right way to implement that, I'll check it later on.

**Comment by StargateMC** [comment] 2016-03-01 22:59
Not sure if the name of the issue states you're going to do the closing or not (for it to match Stargate canon, you wouldn't be able to jump even if you wanted to with an active gate).

Sorry I'm trying to get WarpDrive to function with SGCraft on stargatemc.com (my hobby project)... hence the distractedness haha.

I've had a chat with Greg Ewing regarding the forming/deforming of gates... is there any way for us to trigger onBlockAdded() for gate parts being placed on the other side of a warp? 
At the moment they will not re-form after warping unless broken and placed again.

**Comment by LemADEC** [comment] 2016-03-01 23:45
Sounds like the issue is somewhere else.

**Comment by StargateMC** [comment] 2016-04-04 04:00
Hi LemADEC where would be the best place to put code to check before jump for this? I'll work on a PR :)
Also, to verify things, where could I place code to check on the Stargate post jump?

Sorry I haven't been active lately.

**Comment by LemADEC** [comment] 2016-04-04 08:07
You need to create a LanteaCraftCompat class and implement the rotations there.
There's a method to cancel the pre-jump sequence.
For my pack, we're moving to StargateTech: the code is a bit overcomplicated but way more stable than LanteaCraft.

**Comment by StargateMC** [comment] 2016-04-04 08:09
@LemADEC 
SGCraft is what we are using. Lanteacraft and SGtech2 cant compete for stability and simplicity.
(We use SGtech2.. but have gates disabled)
Whats the method to cancel the pre-jump sequence called? I looked but didn't have any luck finding it.. Call me stupid :P

**Comment by LemADEC** [comment] 2016-04-04 08:12
So you meant the original SGCraft... I didn't try that one on 1.7.x.
isJumpReady() is the name, check here: https://github.com/LemADEC/WarpDrive/blob/MC1.7/src/main/java/cr0s/warpdrive/compat/CompatStargateTech2.java#L41

It'll be implemented on the sequencer with the rewrite, probably this week.

**Comment by LemADEC** [comment] 2016-04-22 21:06
Fixed in c1d5857ba2e89341276521c41cfbc6b88e8e6a18

**Closed as completed** 2016-04-22 21:07 UTC
Labels: improvement
