### ISSUE TITLE
No Stars bug.

### ISSUE THREAD

**Issue by jhammerberg** [LemADEC/WarpDrive#233] opened 2017-01-06 12:02 UTC
There is no stars on my server.
I have warpdrive running with nearly 68 other mods but this has happened when I had just Warpdrive on a server. When I restarted it the space demmension had no stars. How do I fix this and in the next upate please fix it perminatly.

PS: it fixes itself when I start a new world.

**Comment by LemADEC** [comment] 2017-01-06 20:39
The stars background rendering is a client issue that I've been unable to reproduce in dev so far.
If you find a way to reproduce it in 100% cases, I'm very interrested.

**Comment by LemADEC** [comment] 2017-01-07 23:17
The sky rendering was disabled due to a memory leak, it'll be fixed with next update.
a692bb3016f75021633b4fcbc6203b30876fe743

**Closed as completed by LemADEC** 2017-01-07 23:17 UTC

**Comment by jhammerberg** [comment] 2017-01-08 00:51
yay
