### ISSUE TITLE
java.lang.NoClassDefFoundError: net/minecraftforge/common/IRarity

### ISSUE THREAD

**Issue by smallxiaoxiaoB** [LemADEC/WarpDrive#377] opened 2019-05-16 01:48 UTC
```
[09:46:59] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in WarpDrive-1.12.2-1.5.0.-.jar. This is not recommended, @Mods should be in a separate jar from the coremod.

[09:46:59] [main/INFO]: Calling tweak class optifine.OptiFineForgeTweaker

[09:46:59] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions

[09:46:59] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader

[09:46:59] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ClassTransformer

[09:46:59] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ZIP file: E:\敬小龙\字体\1.12.2基础客户端\.minecraft\libraries\optifine\OptiFine\1.12.2_HD_U_E3\OptiFine-1.12.2_HD_U_E3.jar

[09:46:59] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker

[09:46:59] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker

[09:46:59] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker

[09:46:59] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker

[09:46:59] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper

[09:47:02] [main/INFO]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557

[09:47:02] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc

[09:47:02] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper

[09:47:02] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker

[09:47:02] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper

[09:47:02] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker

[09:47:02] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker

[09:47:02] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: getLaunchArguments

[09:47:02] [main/INFO]: Launching wrapped minecraft {net.minecraft.client.main.Main}

[09:47:02] [main/INFO]: Successful injection in net/minecraft/entity/EntityLivingBase

[09:47:03] [main/INFO]: Successful injection in net/minecraft/client/multiplayer/WorldClient

[09:47:03] [Client thread/INFO]: Setting user: small_elf

[09:47:04] [Client thread/INFO]: Successful injection in net/minecraft/entity/item/EntityItem

[09:47:08] [Client thread/INFO]: [OptiFine] *** Reflector Forge ***

[09:47:08] [Client thread/INFO]: [OptiFine] (Reflector) Class not present: mods.betterfoliage.client.BetterFoliageClient

[09:47:08] [Client thread/INFO]: Successful injection in net/minecraft/world/chunk/Chunk

[09:47:08] [Client thread/INFO]: Successful injection in net/minecraftforge/common/ForgeHooks

[09:47:09] [Client thread/INFO]: [OptiFine] *** Reflector Vanilla ***

[09:47:09] [Client thread/WARN]: Skipping bad option: lastServer:

[09:47:09] [Client thread/INFO]: LWJGL Version: 2.9.4

[09:47:11] [Client thread/INFO]: [OptiFine] 

[09:47:11] [Client thread/INFO]: [OptiFine] OptiFine_1.12.2_HD_U_E3

[09:47:11] [Client thread/INFO]: [OptiFine] Build: 20181210-121000

[09:47:11] [Client thread/INFO]: [OptiFine] OS: Windows 10 (amd64) version 10.0

[09:47:11] [Client thread/INFO]: [OptiFine] Java: 1.8.0_211, Oracle Corporation

[09:47:11] [Client thread/INFO]: [OptiFine] VM: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation

[09:47:11] [Client thread/INFO]: [OptiFine] LWJGL: 2.9.4

[09:47:11] [Client thread/INFO]: [OptiFine] OpenGL: GeForce GTX 950/PCIe/SSE2, version 4.5.0 NVIDIA 384.76, NVIDIA Corporation

[09:47:11] [Client thread/INFO]: [OptiFine] OpenGL Version: 4.5.0

[09:47:11] [Client thread/INFO]: [OptiFine] Maximum texture size: 16384x16384

[09:47:11] [VersionCheck/INFO]: [OptiFine] Checking for new version

[09:47:11] [Client thread/INFO]: [Shaders] OpenGL Version: 4.5.0 NVIDIA 384.76

[09:47:11] [Client thread/INFO]: [Shaders] Vendor:  NVIDIA Corporation

[09:47:11] [Client thread/INFO]: [Shaders] Renderer: GeForce GTX 950/PCIe/SSE2

[09:47:11] [Client thread/INFO]: [Shaders] Capabilities:  2.0  2.1  3.0  3.2  4.0 

[09:47:11] [Client thread/INFO]: [Shaders] GL_MAX_DRAW_BUFFERS: 8

[09:47:11] [Client thread/INFO]: [Shaders] GL_MAX_COLOR_ATTACHMENTS_EXT: 8

[09:47:11] [Client thread/INFO]: [Shaders] GL_MAX_TEXTURE_IMAGE_UNITS: 32

[09:47:11] [Client thread/INFO]: [Shaders] Load shaders configuration.

[09:47:11] [Client thread/INFO]: [Shaders] No shaderpack loaded.

[09:47:11] [Client thread/INFO]: [OptiFine] [Shaders] Delayed loading of block mappings after resources are loaded

[09:47:11] [Client thread/INFO]: Forge Mod Loader has detected optifine OptiFine_1.12.2_HD_U_E3, enabling compatibility features

[09:47:11] [Client thread/INFO]: -- System Details --

Details:

	Minecraft Version: 1.12.2

	Operating System: Windows 10 (amd64) version 10.0

	Java Version: 1.8.0_211, Oracle Corporation

	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation

	Memory: 45809000 bytes (43 MB) / 318767104 bytes (304 MB) up to 4294967296 bytes (4096 MB)

	JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx4096m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump

	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0

	FML: 

	Loaded coremods (and transformers): 

WarpDriveCore (WarpDrive-1.12.2-1.5.0.-.jar)

  cr0s.warpdrive.core.ClassTransformer

	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 384.76' Renderer: 'GeForce GTX 950/PCIe/SSE2'

[09:47:11] [Client thread/INFO]: MinecraftForge v14.23.5.2815 Initialized

[09:47:11] [Client thread/INFO]: Starts to replace vanilla recipe ingredients with ore ingredients.

[09:47:12] [VersionCheck/INFO]: [OptiFine] Version found: D3

[09:47:12] [Client thread/INFO]: Replaced 1036 ore ingredients

[09:47:12] [Client thread/INFO]: Searching E:\敬小龙\字体\1.12.2基础客户端\.minecraft\mods for mods

[09:47:13] [Client thread/INFO]: Forge Mod Loader has identified 6 mods to load

[09:47:13] [Client thread/INFO]: Attempting connection with missing mods [minecraft, mcp, FML, forge, WarpDriveCore, warpdrive] at CLIENT

[09:47:13] [Client thread/INFO]: Attempting connection with missing mods [minecraft, mcp, FML, forge, WarpDriveCore, warpdrive] at SERVER

[09:47:14] [Thread-3/INFO]: Using sync timing. 200 frames of Display.update took 150638092 nanos

[09:47:14] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:WarpDrive, Minecraft-Mod-Language-Modpack.zip, ER2K 4k天空包（仅开高清修复时有效）.zip, [1.11.2] R3D CRAFT 32x (v0.3.1).zip

[09:47:16] [Client thread/INFO]: [net.minecraft.init.Bootstrap:func_179870_a:553]: ---- Minecraft Crash Report ----



WARNING: coremods are present:

  WarpDriveCore (WarpDrive-1.12.2-1.5.0.-.jar)

Contact their authors BEFORE contacting forge



// I let you down. Sorry :(



Time: 5/16/19 9:47 AM

Description: Initializing game



java.lang.NoClassDefFoundError: net/minecraftforge/common/IRarity

	at cr0s.warpdrive.WarpDrive.<clinit>(WarpDrive.java:309)

	at java.lang.Class.forName0(Native Method)

	at java.lang.Class.forName(Unknown Source)

	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:526)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.lang.reflect.Method.invoke(Unknown Source)

	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)

	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)

	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)

	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)

	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)

	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)

	at com.google.common.eventbus.EventBus.post(EventBus.java:217)

	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)

	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.lang.reflect.Method.invoke(Unknown Source)

	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)

	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)

	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)

	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)

	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)

	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)

	at com.google.common.eventbus.EventBus.post(EventBus.java:217)

	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)

	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)

	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)

	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)

	at net.minecraft.client.main.Main.main(SourceFile:123)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.lang.reflect.Method.invoke(Unknown Source)

	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)

	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Caused by: java.lang.ClassNotFoundException: net.minecraftforge.common.IRarity

	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)

	at java.lang.ClassLoader.loadClass(Unknown Source)

	at java.lang.ClassLoader.loadClass(Unknown Source)

	... 40 more

Caused by: java.lang.NullPointerException

	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)

	... 42 more





A detailed walkthrough of the error, its code path and all known details is as follows:

---------------------------------------------------------------------------------------



-- Head --

Thread: Client thread

Stacktrace:

	at cr0s.warpdrive.WarpDrive.<clinit>(WarpDrive.java:309)

	at java.lang.Class.forName0(Native Method)

	at java.lang.Class.forName(Unknown Source)

	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:526)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.lang.reflect.Method.invoke(Unknown Source)

	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)

	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)

	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)

	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)

	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)

	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)

	at com.google.common.eventbus.EventBus.post(EventBus.java:217)

	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)

	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.lang.reflect.Method.invoke(Unknown Source)

	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)

	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)

	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)

	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)

	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)

	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)

	at com.google.common.eventbus.EventBus.post(EventBus.java:217)

	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)

	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)

	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)

	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)



-- Initialization --

Details:

Stacktrace:

	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)

	at net.minecraft.client.main.Main.main(SourceFile:123)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

	at java.lang.reflect.Method.invoke(Unknown Source)

	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)

	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)



-- System Details --

Details:

	Minecraft Version: 1.12.2

	Operating System: Windows 10 (amd64) version 10.0

	Java Version: 1.8.0_211, Oracle Corporation

	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation

	Memory: 126232864 bytes (120 MB) / 419430400 bytes (400 MB) up to 4294967296 bytes (4096 MB)

	JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx4096m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump

	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0

	FML: MCP 9.42 Powered by Forge 14.23.5.2815 Optifine OptiFine_1.12.2_HD_U_E3 6 mods loaded, 6 mods active

	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored



	| State | ID            | Version        | Source                        | Signature                                |

	|:----- |:------------- |:-------------- |:----------------------------- |:---------------------------------------- |

	| LC    | minecraft     | 1.12.2         | minecraft.jar                 | None                                     |

	| LC    | mcp           | 9.42           | minecraft.jar                 | None                                     |

	| LC    | FML           | 8.0.99.99      | forge-1.12.2-14.23.5.2815.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |

	| LC    | forge         | 14.23.5.2815   | forge-1.12.2-14.23.5.2815.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |

	| LC    | WarpDriveCore | 1.12.2-1.5.0.- | minecraft.jar                 | None                                     |

	| L     | warpdrive     | 1.12.2-1.5.0.- | WarpDrive-1.12.2-1.5.0.-.jar  | None                                     |



	Loaded coremods (and transformers): 

WarpDriveCore (WarpDrive-1.12.2-1.5.0.-.jar)

  cr0s.warpdrive.core.ClassTransformer

	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 384.76' Renderer: 'GeForce GTX 950/PCIe/SSE2'

	Launched Version: HMCL 3.2.129

	LWJGL: 2.9.4

	OpenGL: GeForce GTX 950/PCIe/SSE2 GL version 4.5.0 NVIDIA 384.76, NVIDIA Corporation

	GL Caps: Using GL 1.3 multitexturing.

Using GL 1.3 texture combiners.

Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.

Shaders are available because OpenGL 2.1 is supported.

VBOs are available because OpenGL 1.5 is supported.



	Using VBOs: Yes

	Is Modded: Definitely; Client brand changed to 'fml,forge'

	Type: Client (map_client.txt)

	Resource Packs: Minecraft-Mod-Language-Modpack.zip, ER2K 4k天空包（仅开高清修复时有效）.zip (incompatible), [1.11.2] R3D CRAFT 32x (v0.3.1).zip

	Current Language: 简体中文 (中国)

	Profiler Position: N/A (disabled)

	CPU: 8x Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz

	OptiFine Version: OptiFine_1.12.2_HD_U_E3

	OptiFine Build: 20181210-121000

	Render Distance Chunks: 24

	Mipmaps: 4

	Anisotropic Filtering: 1

	Antialiasing: 0

	Multitexture: false

	Shaders: null

	OpenGlVersion: 4.5.0 NVIDIA 384.76

	OpenGlRenderer: GeForce GTX 950/PCIe/SSE2

	OpenGlVendor: NVIDIA Corporation

	CpuCount: 8
```

**Comment by LemADEC** [comment] 2019-05-16 07:51
Duplicate of #376 Update your forge version

**Closed as completed by LemADEC** 2019-05-16 07:51 UTC
Labels: not a WarpDrive issue
