### ISSUE TITLE
Cauldron - Chunks not saved after jump

### ISSUE THREAD

**Issue by TovLenin** [LemADEC/WarpDrive#189] opened 2016-06-27 21:00 UTC
Ships tend to loose their parts while jumping. The break occurs on chunk boundaries. The bug appears very often so it is strange that no one has said this before. 

Screenshot: https://pp.vk.me/c630321/v630321749/37222/W9bPWBcMpYM.jpg

**Comment by LemADEC** [comment] 2016-06-27 21:39
Please post your logs during that jump so we can look it up.

**Comment by TovLenin** [comment] 2016-06-28 13:19
http://puu.sh/pIZAO/a6bad36558.log -- log of chunk loosing
http://cs633431.vk.me/v633431113/39a17/Kj1eSnyYi_g.jpg -- screenshot
Also core cooldown works strange, sometimes it doesn' t start just after the jump. Jumps take more time then in Cr0s' version.
And cc software shows wrong amount of energy needed to jump
These are all bugs I can remember so far.

**Comment by LemADEC** [comment] 2016-06-28 20:36
Thanks for the detailed logs.

I'll go one issue at a time :)

1- I've noted a couple crash with TE Energy cells in your logs, looks like a CoFH issue not removing the client interface properly.
Are those Cells in the 'lost' chunks all the time?
Can you clarify the coordinates of the 'lost' chunk on your picture?

```
[15:01:47] [Server thread/INFO]: Removing block cofh.thermalexpansion.block.cell.BlockCell@26c618b3@4 at -627 249 -92
[15:01:47] [Server thread/INFO]: Removing tile entity at -627 249 -92
[15:01:47] [Server thread/INFO]: Tile at -467 249 -252 is class cofh.thermalexpansion.block.cell.TileCell derived from class cofh.thermalexpansion.block.TileReconfigurable
[15:01:47] [Server thread/INFO]: TileEntity cofh.thermalexpansion.block.cell.TileCell at -467 249 -252 is missing a class definition
[15:01:47] [Server thread/WARN]: java.lang.NoClassDefFoundError: net/minecraft/client/audio/ISound
[15:01:47] [Server thread/WARN]:    at java.lang.Class.getDeclaredMethods0(Native Method)
[15:01:47] [Server thread/WARN]:    at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
[15:01:47] [Server thread/WARN]:    at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
[15:01:47] [Server thread/WARN]:    at java.lang.Class.getMethod0(Class.java:3018)
[15:01:47] [Server thread/WARN]:    at java.lang.Class.privateGetMethodRecursive(Class.java:3066)
[15:01:47] [Server thread/WARN]:    at java.lang.Class.getMethod0(Class.java:3018)
[15:01:47] [Server thread/WARN]:    at java.lang.Class.privateGetMethodRecursive(Class.java:3058)
[15:01:47] [Server thread/WARN]:    at java.lang.Class.getMethod0(Class.java:3018)
[15:01:47] [Server thread/WARN]:    at java.lang.Class.privateGetMethodRecursive(Class.java:3058)
[15:01:47] [Server thread/WARN]:    at java.lang.Class.getMethod0(Class.java:3018)
[15:01:47] [Server thread/WARN]:    at java.lang.Class.privateGetMethodRecursive(Class.java:3058)
[15:01:47] [Server thread/WARN]:    at java.lang.Class.getMethod0(Class.java:3018)
[15:01:47] [Server thread/WARN]:    at java.lang.Class.getMethod(Class.java:1784)
[15:01:47] [Server thread/WARN]:    at cr0s.warpdrive.data.JumpBlock.refreshBlockStateOnClient(JumpBlock.java:344)
[15:01:47] [Server thread/WARN]:    at cr0s.warpdrive.event.JumpSequencer.state_removeBlocks(JumpSequencer.java:859)
[15:01:47] [Server thread/WARN]:    at cr0s.warpdrive.event.JumpSequencer.onUpdate(JumpSequencer.java:238)
[15:01:47] [Server thread/WARN]:    at cr0s.warpdrive.event.AbstractSequencer.updateTick(AbstractSequencer.java:24)
[15:01:47] [Server thread/WARN]:    at cr0s.warpdrive.event.WorldHandler.onServerTick(WorldHandler.java:79)
[15:01:47] [Server thread/WARN]:    at cpw.mods.fml.common.eventhandler.ASMEventHandler_516_WorldHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
[15:01:47] [Server thread/WARN]:    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[15:01:47] [Server thread/WARN]:    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
[15:01:47] [Server thread/WARN]:    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:251)
[15:01:47] [Server thread/WARN]:    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:862)
[15:01:47] [Server thread/WARN]:    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
[15:01:47] [Server thread/WARN]:    at java.lang.Thread.run(Thread.java:745)
[15:01:47] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.client.audio.ISound
[15:01:47] [Server thread/WARN]:    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
[15:01:47] [Server thread/WARN]:    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[15:01:47] [Server thread/WARN]:    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[15:01:47] [Server thread/WARN]:    ... 25 more
```

2- Core cool-down depends on your jump distance.
Technically, if you jump in sequence, the cool-down message won't show up immediately, as it waits for round numbers of 10 seconds initially. Also, due the large number of tile entities 'activating' right after the jump, the CC boot speed fluctuate a bit.
Or did I miss your point?

3- The cool-down was much shorter in Cr0s version due to some client/server sync issues.
For the record, default configuration is to keep server CPU below 50% during jump, the cool-down is to encourage players strategy and reduce the lag.
If you meant something else, please explain :)

4- In Cr0s version, CC was computing energy cost in LUA. That computation was inaccurate for various reasons.
In 1.7.10, I've updated the API so the energy cost displayed is actually the one computed by the mod.
If you see wrong energy computation, please share how you reproduce it :)

**Comment by TovLenin** [comment] 2016-06-28 21:28
There were only vanilla blocks in the lost chunk.

**Comment by LemADEC** [comment] 2016-06-28 23:07
What other mods are in your packs?
Is it a pure Forge server or something like Cauldron?

**Comment by TovLenin** [comment] 2016-06-29 05:19
http://cs633431.vk.me/v633431113/39bba/EL8692GR3iM.jpg
Oh, there is cauldron

**Comment by LemADEC** [comment] 2016-06-29 07:49
We are unable to reproduce your issue so far.

Are you playing in Single player or in Multiplayer?
Can you post the full logs of the server, notably the boot part?
Can I download your pack somewhere?

**Comment by MaksBobs** [comment] 2016-06-29 08:59
> Are you playing in Single player or in Multiplayer?

Multiplayer.

> 1- I've noted a couple crash with TE Energy cells in your logs, looks like a CoFH issue not removing the client interface properly.
> Are those Cells in the 'lost' chunks all the time?

No. Some players do not even use TE cells or mechs on their ships.

This is main issue on our server - about 80% of any jumps end with pierced ships. If your ship is large, you can farewell to 5 chanks for example.

> Is it a pure Forge server or something like Cauldron?

 Cauldron

> Can you post the full logs of the server, notably the boot part?

Later.

> Can I download your pack somewhere?

Is mods folder enough?

**Comment by TovLenin** [comment] 2016-06-29 19:19
http://puu.sh/pK3ER/f12c961917.log
https://www.dropbox.com/s/8lzycultkz8bixj/Kauldron.zip?dl=0

**Comment by LemADEC** [comment] 2016-06-29 21:21
Thanks for the detailed answer.
It appears you've chunk-gc enabled in your bukkit.yml, this is not recommended on forge server as it force chunk unloading without prior saving. Please disable it and see how it goes.

**Comment by LemADEC** [comment] 2016-07-04 08:09
Is it fixed now?

**Comment by MaksBobs** [comment] 2016-07-05 12:42
Well, not really. We made as you said, but still some accidents happend. Admin decided to move to Thermos. Players do not want to destroy their ships and are not jumping alot, so there is not enough information for statistics to answer. Only once I jumped and found one chunk missing. At least i found lost piece on the previous location and returned. Unfortunately I have no logs.

**Comment by LemADEC** [comment] 2016-07-05 19:18
Your new occurrence was after the Thermos switch or before?
Have you been able to reproduce the issue in single player?

**Comment by MaksBobs** [comment] 2016-07-05 20:00
It occured after the Themos switch.
No, haven't tried. Few days everything was normal.

**Comment by LemADEC** [comment] 2016-07-05 22:33
Can you confirm chunk-gc is still disabled? it may remains online if it's changed without a full shutdown.
If it still happens, we'll have to narrow down the mod/plugins list.

**Comment by StargateMC** [comment] 2016-07-14 07:21
I'm seeing this one too. Will test chunk-gc - my players are actively bugtesting all our mods/plugins used.

**Comment by StargateMC** [comment] 2016-07-14 07:35
chunk-gc has no effect. we have it disabled already :)

**Comment by LemADEC** [comment] 2016-07-14 07:46
We've never seen it on our server since I took over the mod, about 2 years ago, except for that chunk-gc option.
Try to reproduce it with no plugins, then remove mods?

**Comment by StargateMC** [comment] 2016-07-14 12:45
This seems to be caused by Bukkit plugins not handling so many break / place events at once - I got one of our custom plugins to ignore the WD player and things became a lot better. Could have just made the problem less significant tho.

Maybe as a precaution allow people the option to only have one block break / place fire per chunk affected by a ship? Most protection plugins work based on chunk anyway.

**Comment by TovLenin** [comment] 2016-07-14 15:45
We have no protection plugins and yet chunks are lost.

**Comment by LemADEC** [comment] 2016-07-14 22:34
Those the issue happens only during same dimension jump?

**Comment by StargateMC** [comment] 2016-07-14 22:59
Have seen I in both cross and same dim.

Tov I didn't imply you had a protection plugin don't worry :) I was referring to any plugin that monitors break or place events in Bukkit.

A 3000 block ship throws 3000 break and place events approx... 6k events total - All at once haha

**Comment by LemADEC** [comment] 2016-07-14 23:18
should be split over 5+ ticks, so not all at once ;)

**Comment by StargateMC** [comment] 2016-07-15 00:16
Hey Lemadec - I understand forge does it over 5+ ticks but Bukkit does its events in the main thread. Shitty limitation haha

**Comment by LemADEC** [comment] 2016-07-18 08:08
We did 50+ jumps with excessively large ships and have yet to reproduce the issue on our test server.
From the difference between our modpacks, the following are suspicious. I've put in bold the prime suspects:
**1.7.10/ForgeRelocation
1.7.10/ForgeRelocationFMP**
1.7.10/MrTJPCore
ArchitectureCraft
Aroma1997Core
AsieLib
bclib
BigReactor
Biomes'o plenty
buildcraft
**ClimateControl**
Computronics
**dimensional-anchor**
forestry
**Framez**
gendustry
generators
GraviSuite
IC2NuclearControl
immersiveintegration
legacyjavafixer
ModControl
ModTweaker2
NetherOres
OpenComputers
OpenPeripheral
OreDictionaryConverter
PracticalLogistics
ProjectRed
SonarCore
StevesCarts2
Uncomplication

@TovLenin legacyjavafixer is only applicable to Java 1.6.4, you should remove it :).
@DraksterAU which of those mods are common with your pack?

**Comment by StargateMC** [comment] 2016-07-18 08:31
GraviSuite, ProjectRed, OpenComputers, OpenPeripheral, GraviSuite, Forestry, ArchitectureCraft, TJPCore.

Biomes o Plenty and dimensional anchor really shouldn't be used on a Cauldron server. Same for Steves carts (weird shit happens)..... Other than that everything _should_ work.

If you want carts: RailCraft is tested and works.
If you want chunk loaders: Railcraft is tested and works :)
Biomes o plenty will work if you do not use a bukkit provided dimension (multiworld/multiverse plugins).... otherwise it plays up.

Sorry for the additional info.... might not be helpful.

**Comment by StargateMC** [comment] 2016-07-18 09:30
@LemADEC Stupid Q... but did you try that using Thermos? Or Vanilla forge?

**Comment by LemADEC** [comment] 2016-07-18 19:26
We've been using Cauldron/Thermos for the last 2 years.

**Comment by StargateMC** [comment] 2016-07-18 21:30
What versions?
There are some changes to chunk data in the more recent ones. Unnecessary changes :(

**Comment by LemADEC** [comment] 2016-07-18 23:06
We did our tests this week end with build 57.
Have you tried reproducing it with a plain Forge server?

**Comment by StargateMC** [comment] 2016-07-19 01:10
I can't set up a test forge sever - the error doesn't happen often enough that I can find it solo in a single session.
Can you try b46?
Most of us don't use anything later because it breaks Bukkit dimensions n other weird stuff. Chunk issues galore!

**Comment by StargateMC** [comment] 2016-07-19 01:10
They keep making performance improvements but are gradually reducing the compatibility with plugins and mods that they had... Haha

**Comment by LemADEC** [comment] 2016-07-19 05:55
b46 is too old, we need fixes implemented later on.
I was told the issue being quite frequent, now you're telling him it's not ?!?

**Comment by StargateMC** [comment] 2016-07-19 06:45
I had a plugin enabled that wrote a time stamp to a file each time a block break or place occurred.

After making that plugin ignore the warpdrive fake player in Bukkit, we haven't had a recurrence.

I think it's something to do with forge perhaps dropping the request to modify the chunk if bukkit takes too long? It's almost like its load based.

Up til then it was happening a couple of times a day.

**Comment by StargateMC** [comment] 2016-07-19 06:48
So you know I run a dual Xeon quad core / 32gb ram / 480mbps read/write ssd server. Server specifications shouldn't be letting me down.

**Comment by LemADEC** [comment] 2016-07-20 22:39
Assuming it's lag related, we could build a massive lag machine in single player and reproduce it?

**Comment by StargateMC** [comment] 2016-07-21 00:32
I think it's lag related and specific to the Bukkit side of cauldron. I haven't been able to reproduce in SP or forge.

**Comment by StargateMC** [comment] 2016-07-21 00:32
Try though!! :)

**Comment by LemADEC** [comment] 2016-07-30 13:49
Cooldown messaging is fixed in next version.

**Comment by LemADEC** [comment] 2016-07-30 13:51
I need answers on the following points to move further:
- Those the issue happens only during same dimension jump?
- Is the issue reproductible with Forge dedicated server with massive lag?
- Is the issue reproductible in single player with massive lag?

**Comment by StargateMC** [comment] 2016-08-27 08:00
Havent seen this in B58 of Thermos. They made improvements to chunk saving etc in the last few builds... maybe it helps?

**Comment by LemADEC** [comment] 2016-08-27 22:26
that issue doesn't make much sense to me so far

**Comment by LemADEC** [comment] 2016-12-08 00:08
Unable to reproduce so far, closing as nofix

**Closed as completed by LemADEC** 2016-12-08 00:08 UTC
Labels: Pending user feedback
