### ISSUE TITLE
Can't jump because protected land?

### ISSUE THREAD

**Issue by ghost** [LemADEC/WarpDrive#211] opened 2016-09-15 04:18 UTC
For some reason it says theres not enough room to jump in protected land, but Im like 50 blocks off the ground and still getting this problem.
"Ship is entering protected land!" "Not enough space after adjustment" or something like that.

**Comment by LemADEC** [comment] 2016-09-15 09:39
Protection plugins usually protects the whole vertical range of chunk, you need to jump horizontally to avoid it.

**Comment by ghost** [comment] 2016-09-16 02:20
I've tried everything so is there anyway you could explain? My server still gets same message no matter what.

**Comment by LemADEC** [comment] 2016-09-16 08:37
You need to provide more details, like versions and logs...

**Comment by ghost** [comment] 2016-09-16 11:48
that isn't gonna tell you much cause there's nothing showing up in the logs except "ship is entering protected land! Aborting jump!" And also I wouldn't use a old version cause I can see the problems were even worse in the old versions.

**Comment by ghost** [comment] 2016-09-16 11:56
Aka I'm using 1.3.29. It's the same issue I believe as the other guy who made a post back in May. You then released the "fix" July 30/31st.

**Comment by ghost** [comment] 2016-09-16 12:08
https://github.com/LemADEC/WarpDrive/issues/174

Also, we have tested every dimension, protected or not. It gives same message over and over with no change. I have tested it and it doesnt work in space either.

"Ship is entering protected area, Not enough space after adjustment, jump aborted!"

**Comment by LemADEC** [comment] 2016-09-16 19:29
You need to enables logs to have them. Also they say much more than the few lines you've listed here.

**Comment by ghost** [comment] 2016-09-16 20:15
[16:12:58] [Server thread/INFO]: Profiling StarMapRegistry cleanup: 1.14 ms
[16:12:58] [Server thread/INFO]: TileEntityShipCore 'USS MAH DICK' @ 'faction' (-867 110 -1500) Performing basic jump of 80 blocks inside (-872, 109, -1502) to (-865, 112, -1497) with an actual mass of 80 blocks toward direction 666 over 1 blocks.
[16:12:58] [Server thread/INFO]: Profiling Jump.chunkLoading: 4.808 ms
[16:12:58] [Server thread/INFO]: Profiling Jump.saving: 6.126 ms
[16:12:58] [Server thread/INFO]: JumpSequencer/1967663752 '95c975b4-2252-4489-84e9-5c17adce8da7:USS MAH DICK' @ 'faction' (-867 110 -1500) #4 Saving ship state prior to jump in warpDrive_schematics/auto/USS MAH DICK_2016-09-16_16h12m58s811.schematic
[16:12:58] [Server thread/WARN]: java.io.IOException: The system cannot find the path specified
[16:12:58] [Server thread/WARN]:  at java.io.WinNTFileSystem.createFileExclusively(Native Method)
[16:12:58] [Server thread/WARN]:  at java.io.File.createNewFile(Unknown Source)
[16:12:58] [Server thread/WARN]:  at cr0s.warpdrive.event.JumpSequencer.writeNBTToFile(JumpSequencer.java:455)
[16:12:58] [Server thread/WARN]:  at cr0s.warpdrive.event.JumpSequencer.state_borders(JumpSequencer.java:436)
[16:12:58] [Server thread/WARN]:  at cr0s.warpdrive.event.JumpSequencer.onUpdate(JumpSequencer.java:197)
[16:12:58] [Server thread/WARN]:  at cr0s.warpdrive.event.AbstractSequencer.updateTick(AbstractSequencer.java:24)
[16:12:58] [Server thread/WARN]:  at cr0s.warpdrive.event.WorldHandler.onServerTick(WorldHandler.java:79)
[16:12:58] [Server thread/WARN]:  at cpw.mods.fml.common.eventhandler.ASMEventHandler_264_WorldHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
[16:12:58] [Server thread/WARN]:  at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[16:12:58] [Server thread/WARN]:  at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
[16:12:58] [Server thread/WARN]:  at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:251)

**Comment by ghost** [comment] 2016-09-16 20:15
[16:12:58] [Server thread/WARN]:  at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:862)
[16:12:58] [Server thread/WARN]:  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
[16:12:58] [Server thread/WARN]:  at java.lang.Thread.run(Unknown Source)
[16:12:58] [Server thread/INFO]: Profiling Jump.borders: 2.13 ms
[16:12:58] [Server thread/INFO]: TileEntityShipCore 'USS MAH DICK' @ 'faction' (-867 110 -1500) messageToAllPlayersOnShip: Ship is entering a protected area
Not enough space after adjustment, jump aborted!
[16:12:58] [Server thread/INFO]: Profiling Jump.transformer: 46.935 ms
[16:12:59] [Server thread/INFO]: pather1882 issued server command: /cast kamehameha x
[16:13:02] [Server thread/INFO]: [@QuestCompletion: TP adding 16000 success for Asarris]
[16:13:02] [Server thread/INFO]: < [God_Slayer]GodMog> yeah
[16:13:06] [Server thread/INFO]: DBC-Info: entity.jinryuudragonblockc.hell01.name has been killed by DoubleTheGreat
[16:13:08] [Server thread/INFO]: < [GodofDestruction]Finn[Universe_9]> cus peeps where setting fire to everything
[16:13:11] [Server thread/WARN]: DoubleTheGreat moved wrongly!
[16:13:13] [Server thread/INFO]: Connorc325 has died
[16:13:13] [Server thread/INFO]: Connorc325 fell out of the world
[16:13:13] [Server thread/INFO]: < [GodofDestruction]Finn[Universe_9]> it was annoying
[16:13:14] [Server thread/INFO]: Matched Spell Component: class am2.spell.components.PhysicalDamage
[16:13:14] [Server thread/INFO]: < [GodofDestruction]lllVinyllll> yo finn
[16:13:14] [Server thread/INFO]: [@QuestCompletion: TP adding 3000 success for DoubleTheGreat]
[16:13:15] [Server thread/INFO]: pather1882 issued server command: /cast kamehameha x
[16:13:16] [Server thread/INFO]: < [Arcosian]Deadpullpl[Half-Saiyan]> yea

**Comment by LemADEC** [comment] 2016-09-16 23:58
We need the full logs

**Comment by ghost** [comment] 2016-09-17 00:36
I don't see how a full log makes any different from when I tested the warp drive and copied everything from then till after it failed. https://www.dropbox.com/s/0lepssrx06prgoh/2016-09-15-2.log.gz?dl=0

**Comment by StargateMC** [comment] 2016-09-17 07:13
@Halokiller38 Does your server run worldguard? If so you will need to allow the WarpDrive fakeplayer to break blocks on the **global** region.... or remove the region. That region covers all unclaimed areas.

(Just an idea..)

**Comment by LemADEC** [comment] 2016-09-17 10:13
The WorldGuard **global** region is required by the plugin, you don't want to remove it. WorldGuard allows fake players globally through it's configuration:
    fake-player-build-override: true

[19:37:20] [main/INFO]: Forge Mod Loader version 7.99.4.1517 for Minecraft 1.7.10 loading
Your forge version is 1517, latest is 1614.

Forge don't need LegacyJavaFixer anymore.

[19:37:37] [Server thread/WARN]: [19:37:37][SEVERE][noppes.npcs.enchants.EnchantInterface:49] java.lang.IllegalArgumentException: Duplicate enchantment id! class noppes.npcs.enchants.EnchantDamage and class am2.enchantments.EnchantMagicResist Enchantment ID:100
You've overlapping enchantment ids, random crashes will happen.

[19:37:43] [Server thread/INFO]: This server is running KCauldron version 1.7.10-1517.169 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)
You're using a very old version of KCauldron. At least use latest, or switch to Thermos.

[19:37:47] [Server thread/ERROR]: Could not load 'plugins\CS-CoreLib_v1.3.1.jar' in folder 'plugins'
You've an invalid plugin.

[19:39:14] [Server thread/ERROR]: Could not pass event VehicleDamageEvent to GriefPrevention v9.1
Your protection plugin is incompatible with your setup. Try GriefPreventionPlus instead.

[20:00:43] [Server thread/INFO]: JumpSequencer/1403085952 '634db1bf-2d71-4c3c-b334-9c1c0c0d552e:God Slayer's Shaft' @ 'world' (840 93 557) #4 Saving ship state prior to jump in warpDrive_schematics/auto/God Slayer's Shaft_2016-09-15_20h00m43s194.schematic
[20:00:43] [Server thread/WARN]: java.io.IOException: The system cannot find the path specified
You need to create an 'auto' folder in the 'warpDrive_schematics' folder to enable auto-saving.

[20:00:43] [Server thread/INFO]: TileEntityShipCore 'God Slayer's Shaft' @ 'world' (840 93 557) messageToAllPlayersOnShip: Ship is entering a protected area
Not enough space after adjustment, jump aborted!

We're still missing the WarpDrive logs, remember to enable them in the mods configuration.

You're using WorldGuard and GriefPrevention for area protection, check that the global area/wilderness allows to place blocks. The mod use a FakePlayer, WG has a global setting for it (see above).

**Comment by StargateMC** [comment] 2016-09-17 10:15
@lemadec If you do that it bypasses claimed land too.
It is not required... it is optionally enabled on a per world basis.

**Comment by ghost** [comment] 2016-09-17 16:35
fake-player-build-override: true was true to begin with. 
Alrighty we've tested it with everything said above and still doesnt work but we did get the logs you need. 

https://www.dropbox.com/s/wq3un6dcrjxzuc7/latest.log?dl=0

My I see why this is disabled, even on a 16 gb - 24 gb server it causes extreme lag.

**Comment by LemADEC** [comment] 2016-09-18 09:10
I see you've fixed some of my previous message.
You can keep Energy logs off, those are the ones lagging your server.

Try disabling plugins one by one to see which one is blocking you, starting with GriefPrevention, BuyRegion, WorldGuard, EssentialsAntiBuild, and EssentialsProtect. Once you've found it, post your plugins configurations.

**Comment by ghost** [comment] 2016-09-18 18:20
We've disabled every protection plugin and still are having the problem, even without WorldGuard we still are getting the problem. Here is the log.

https://www.dropbox.com/s/emgpmalmpj8tj5b/latest%281%29.zip?dl=0

Edit: Currently we are testing without all plugins and so far it worked finally! We are slowly adding all of our plugins 1 by 1 to see what it is.

**Comment by ghost** [comment] 2016-09-18 22:43
We've discovered that it was the plugin YAPP: https://mods.curse.com/bukkit-plugins/minecraft/yapp and also that ChestShop causes the server to crash when you jump.

**Comment by StargateMC** [comment] 2016-09-18 23:09
Allow the [WarpDrive] fakeplayer to bypass YAPP - it looks like it protects a whole heap of blocks randomly... there are no 'areas' to speak of?
To be clear your server is grinding to a halt, not crashing?
@LemADEC Do you cancel the warp upon finding the first cancelled break/place event, or keep going?

**Comment by ghost** [comment] 2016-09-18 23:51
We just removed yapp, its kinda pointless. And it completely crashes server with the message "Server Closed" When you jump with the plugin ChestShop.

The reason YAPP stops the protection cause it uses its own Per-World Perms.

**Comment by LemADEC** [comment] 2016-09-18 23:57
Jump is adjusted as soon as the first block is found to be protected.

YAPP seems redundant with your other plugins, not quite sure why you want to use it here.
What's your crash logs with ChestShop?

**Comment by ghost** [comment] 2016-09-19 00:05
We had YAPP merely for the purpose of colored names so we are fine without it Lol. And idk we didn't get it. We just kinda moved on but I can explain what happens.

Basically as soon as the jump occurs, the chunk becomes corrupt due to the blocks moving. When this happens, the players in that vicinity will cause the server to crash and if they rejoin they will continually make the server crash or well, say "Server Closed". Upon moving the players coords they can rejoin, but the chunk that the jump took place is corrupted forever, and if you are to go back you cause the server to close/crash.

**Comment by StargateMC** [comment] 2016-09-19 03:19
Any chance you'd consider cancelling the warp (or have a config for it) if you run into protected areas?

Reason being is if the destination is claimed it is highly likely at least a 3x3 - 5x5 around the are is claimed also which results in huge amounts of lag caused by plugins.
It's rare for a claim by a player to not exist over several chunks.

**Comment by LemADEC** [comment] 2016-09-19 08:43
You can't predict if the ship is close or right in the middle of a protected area.
Same goes with collisions.

**Comment by LemADEC** [comment] 2016-09-19 20:17
Assuming a whole area is protected, only block is tested per possible jump distance, which is pretty much nothing compared to an actual jump.

**Comment by LemADEC** [comment] 2016-09-29 01:01
Looks like it was a plugin issue, closing

**Closed as completed by LemADEC** 2016-09-29 01:01 UTC
Labels: not a WarpDrive issue
