### ISSUE TITLE
Sand spawning in space

### ISSUE THREAD

**Issue by TheNumenorean** [LemADEC/WarpDrive#90] opened 2015-09-09 23:32 UTC
![2015-09-09_16 30 49](https://cloud.githubusercontent.com/assets/809047/9776728/514fed96-5710-11e5-9a79-e4c7c3f40e4f.png)

**Comment by LemADEC** [comment] 2015-10-05 00:16
Can't reproduce

**Comment by LemADEC** [comment] 2015-12-12 03:46
A memory leak on worldObj was fixed.
Issue can't be reproduced before nor after that fix.
Closing until we can actually reproduce it.

**Closed as completed by LemADEC** 2015-12-12 03:46 UTC
Labels: bug, help wanted
