### ISSUE TITLE
force field projectors (half and full) not responding

### ISSUE THREAD

**Issue by ghost** [LemADEC/WarpDrive#224] opened 2016-11-15 18:17 UTC
My issues:
The main laser that should be boosted fires immidiately if the targeting camlaser hits solid world (im not sure if its an very speedy projectile or its an hitscan system) and after the main fired the boosters fire and you hear the boosted laser sound but no second laser and the player doesnt get camera position for view on normal camera and laser+camera 0_0

And for some reason if the forcefield has:
A shape that it tells me its half shape
A valid frequency using tuning fork
Enough energy (it seems it cant get completely full for some reason even if its getting powered by creative sources)
1 range upgrade
A redstone signal

Also its not making its hunming sound

1.7.10 forge:
I am using warpdrive latest and 
Thermal expansion+others
Factorization
Extrautilities
Draconic evolution
Simply jetpacks
Flansmod
Techguns mod
Opencomputers
Computercraft
Gregs sg craft
Matter overdrive
Quiverbow
Fusion warfare
Fission warfare
Tinkers construct
Avp
And more mods that are common in big famous modpacks

**Comment by LemADEC** [comment] 2016-11-15 23:24
I don't quite understand what your problems are here, so I'll just pick a guessing.

A laser is an energy beam travelling instantaneously. Any solid block on the way will be considered a target.
As with most weapons, keep in mind that your line of sight isn't aligned with the laser beam itself.

Redstone is ignored by the forcefield projector.
You can't project a forcefield in a protected area (spawn, protection plugins, etc.).
A single sided projector will only project on one side, hence making an half shape.
A double died projector will covers both opposing sides, hence forming a full shape.

Latest isn't a version number. We need the actual version.
Please explain step by step what you're doing, what you expect and what's observed.
Also, there should be one problem per issue.

**Comment by ghost** [comment] 2016-11-16 09:07
I have warpdrive version 1.3.29
The shield issue:
What i have seen:
There is no double sided forcefield
Any half projectors being placed become full projector blocks(not the item)
Full doesnt do anything even if its valid and has energy or gets an activation command by cc or oc
Full only has 1 electromagnetic projection side
It says the shape is an half sphere

And in version 1.3.25 or .28 i believe you can sneak throug projected forcefield blocks if its not upgraded with pull or push.

So basicly it generates nothing and isnt doing anything and is glitchy

The laser issue after some experiments:

When the lasercam hits a valid object the main laser fires. after the main fired the boosters boost it. When the main fires i hear regular laser sound (i used sound remover blocks for lasercam) and if it gets boosted after it shot i hear the boosting laser sound but no extra laser.
And because of the laser visually traveling slowly its hard to know if its instantly boosted and the main is firing an bigger energy burst

The cam issue:
My player view isnt being placed above the warpdrive camera or laser+camera if i click the monitor.

I request the laser being visually instant and the players cam being placed in front of warpdrivelasercamera/warpdrivecamera (make a check for the laser+camera to not hit the players view because it would be not so happy ending)

**Comment by LemADEC** [comment] 2016-11-16 09:38
Latest is 1.3.30.

Forcefield projectors work fine on official server. You probably have an interfering mod in your pack. Try to reproduce with only WarpDrive and OpenComputers.

Where did you get 1.3.25 and 1.3.28? those are internal, never published, versions.

Laser visual is always delayed due to network latency. It's animated so players can feel the direction of propagation.
Which programs are you using to control your lasers?
It's not recommended to use same laser for Targeting and Main shooting since your boosters won't have time to reload in most cases.

Camera place players view from above the block because the game is mostly flat and we need more precision horizontally then vertically. Placing it in front will add errors on both axis which is way worse.
This imply that you leave a transparent block above the camera since Vanilla doesn't accept viewing from inside a block.

**Comment by ghost** [comment] 2016-11-16 09:41
I got warpdrive 1.3.25 and .28 from some git
And i used cc command computers and i testec oc same results
My player view isnt set at all it looks like i get teleported to spot where i click immidiately.
And i have no plugins or whatsoever installed
Whats the official server ip? It might be some fps bug or clientside bug

**Comment by ghost** [comment] 2016-11-16 15:08
where can i download warpdrive 1.3.30?
my version with error was 1.3.29

**Comment by LemADEC** [comment] 2016-11-17 01:01
Official modpack is available on Technic launcher. Server IP is preloaded. Check here for details: http://www.worldwarminecraft.net/wwminfo

1.3.30 is available on CurseForge: https://minecraft.curseforge.com/projects/warpdrive/files

**Comment by ghost** [comment] 2016-11-17 17:18
Thank you. But for some reason the force fields still arent generating anything in warpdrive version 1.3.30 ill try installing ic2 and other dependencies
The rest is fixed by installing latest version (1.3.30)

**Comment by LemADEC** [comment] 2016-11-17 21:47
what does the guide says when you right click the projector with an empty hand?

**Comment by ghost** [comment] 2016-11-18 08:27
Apply an upgrade/dismount when holding shift?

Upgrading or applying shape works fine.

Its just not doing its job, no plugins or protection systems. Btw i cant even make it a double sided projector

I have warpdrive 1.3.30

**Comment by LemADEC** [comment] 2016-11-18 08:39
I said right click with an empty hand. Not with shift. Not with an shape or upgrade in hand.

Double sided are crafted as such, not upgraded. Check your recipes.

**Comment by ghost** [comment] 2016-11-18 08:40
Sorry but it seems right clicking  it does completely nothing

**Comment by LemADEC** [comment] 2016-11-18 09:39
![image](https://cloud.githubusercontent.com/assets/4776032/20425515/346cea4a-ad7b-11e6-8538-386f184657d9.png)

Remove mods until you get the guide message then

**Comment by LemADEC** [comment] 2016-11-18 09:39
and make sure you are far away from spawn

**Comment by ghost** [comment] 2016-11-18 09:39
Well the guide in the chat is popping up 
I went to 14 different dimensions and no results

**Comment by LemADEC** [comment] 2016-11-18 21:12
What does the guide say?

**Comment by ghost** [comment] 2016-11-19 08:14
Basic force field half projector:
Energy level: 89.900/90 000
Beam frequency 105 is valid
Shape is an half sphere
No upgrade installed

For some reason energy level never gets to 90.00 (or max of the block) Even if there is a creative energy cell next to it.

**Comment by LemADEC** [comment] 2016-11-19 15:01
Energy units differs between producer and consumer, hence the rounding when close to max capacity. This is to prevent constant leak or duping of energy.

Enable all logs in the mod configuration, reboot the game and post your server logs.

**Comment by ghost** [comment] 2016-11-21 06:41
I will try when i have time.

**Comment by LemADEC** [comment] 2016-12-08 00:04
so?

**Comment by ghost** [comment] 2016-12-08 06:41
Still completely nothing :(
Opencomputers doesnt even catch all the components

**Comment by LemADEC** [comment] 2016-12-08 09:34
OC limits the number of components per CPU, you've probably reached the limit.

**Comment by ghost** [comment] 2016-12-08 09:36
No i connected only 1 component and one computer. I have no idea what is wrong with warpdrive on my side but it refuses to project with other mods. But i think its the thermal expansion cofh api problem. I will try using extra utilities or something else as rf power supplyment

**Comment by LemADEC** [comment] 2016-12-08 20:34
Pretty sure I've asked for logs ^

**Comment by LemADEC** [comment] 2017-01-07 23:44
No update for 4+ weeks, Closing until logs are provided

**Closed as completed by LemADEC** 2017-01-07 23:44 UTC
Labels: Pending user feedback
