### ISSUE TITLE
crash upon entering the end with ship

### ISSUE THREAD

**Issue by kohlth** [LemADEC/WarpDrive#380] opened 2019-06-25 18:36 UTC
here is the crash log

[crash-2019-06-25_13.21.27-server.txt](https://github.com/LemADEC/WarpDrive/files/3326815/crash-2019-06-25_13.21.27-server.txt)

**Comment by LemADEC** [comment] 2019-06-25 19:33
Java Version: 1.8.0_51, Oracle Corporation
=> Java needs to be updated or use another launcher

Forge 14.23.5.2838 162 mods loaded
WarpDrive-1.12.2-1.5.4.-.jar 

```
java.lang.NullPointerException: Exception in server tick loop
	at com.google.common.collect.ImmutableSetMultimap$Builder.putAll(ImmutableSetMultimap.java:317)
	at net.minecraftforge.common.ForgeChunkManager.forceChunk(ForgeChunkManager.java:817)
	at cr0s.warpdrive.event.JumpSequencer.forceTargetChunks(JumpSequencer.java:426)
	at cr0s.warpdrive.event.JumpSequencer.state_loadTargetChunks(JumpSequencer.java:759)
	at cr0s.warpdrive.event.JumpSequencer.onUpdate(JumpSequencer.java:300)
	at cr0s.warpdrive.event.AbstractSequencer.updateTick(AbstractSequencer.java:24)
	at cr0s.warpdrive.event.WorldHandler.onServerTick(WorldHandler.java:121)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2477_WorldHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:266)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:712)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)
```

Last line in the mod:
https://github.com/LemADEC/WarpDrive/blob/MC1.12/src/main/java/cr0s/warpdrive/event/JumpSequencer.java#L426
NPE is actually inside forge chunk loading map update:
```java
    public static void forceChunk(Ticket ticket, ChunkPos chunk)
    {
        if (ticket == null || chunk == null)
        {
            return;
        }
        if (ticket.ticketType == Type.ENTITY && ticket.entity == null)
        {
            throw new RuntimeException("Attempted to use an entity ticket to force a chunk, without an entity");
        }
        if (ticket.isPlayerTicket() ? !playerTickets.containsValue(ticket) : !tickets.get(ticket.world).containsEntry(ticket.modId, ticket))
        {
            FMLLog.log.fatal("The mod {} attempted to force load a chunk with an invalid ticket. This is not permitted.", ticket.modId);
            return;
        }
        ticket.requestedChunks.add(chunk);
        MinecraftForge.EVENT_BUS.post(new ForceChunkEvent(ticket, chunk));

        ImmutableSetMultimap<ChunkPos, Ticket> newMap = ImmutableSetMultimap.<ChunkPos,Ticket>builder().putAll(forcedChunks.get(ticket.world)).put(chunk, ticket).build();
```
=>
```java
    public Builder<K, V> putAll(Multimap<? extends K, ? extends V> multimap) {
      for (Entry<? extends K, ? extends Collection<? extends V>> entry :
          multimap.asMap().entrySet()) {       // *** NPE is here ***
        putAll(entry.getKey(), entry.getValue());
      }
      return this;
    }
```

162 is way too many mods.
=> try to reproduce with only a few mods

Crash happens during jump, we need the ship stats.
=> post debug logs related to the crash

**Comment by LemADEC** [comment] 2019-06-27 00:38
unable to reproduce with Space architect 1.3.3

**Comment by LemADEC** [comment] 2019-07-13 19:04
Unable to reproduce, no update for 18 days, closing

**Comment by mskorzhinskiy** [comment] 2019-08-28 20:42
I think this issue deserves to be reoppened.

I have reproduced it on a clean minecraft with only warpdrive and opencomputers. No changes to any config, all defaults. Although, one thing is that I've entered end (or pluto?) using '/space' command, without actually traveling.

Crash log:
[warpdrive-test-pluto-crash.log](https://github.com/LemADEC/WarpDrive/files/3552800/warpdrive-test-pluto-crash.log)

Modpack with save and ship ready to jump and crash:
[warpdrive-test-1.0.0.zip](https://github.com/LemADEC/WarpDrive/files/3552802/warpdrive-test-1.0.0.zip)

**Comment by LemADEC** [comment] 2019-08-28 21:50
Please try to reproduce with latest java and WarpDrive 1.5.8 (pending approval), notably see how frequently it is reproduced

**Comment by mskorzhinskiy** [comment] 2019-08-28 22:14
Updated to 1.5.8, newly created universe.

I've tried 3 times to use old universe, from times when 1.5.7 was installed and 4 times with fresh created universe. Still crashing.

Also I've made an attempt of removing forcedchunks.dat as it was suggested here: https://forums.ftbwiki.org/topic/2884-server-crashed-and-wont-start/ Crashed again.

I will try to downgrade forge versions, but I do not really believe that it will help. Google reports quite a lot of these bugs in very different  mods. Even if it is a bug inside a forge, then it is the old one...

**Comment by LemADEC** [comment] 2019-08-28 23:20
try without warpdrive, using `/forge setdimension` to reach the end or the nether?

**Comment by mskorzhinskiy** [comment] 2019-08-29 08:44
Works prefectly with and without warpdrive. I think I mentioned it on a discord already, but anyway, just FYI and for the record.

Jumping to any custom dimension with warp drive causing this crash. Teleporting to any dimension using /space or /forge setdim commands always worked without any major problem. Also leaving a dimension with warp drive work perfectly fine.

So the only situation when this crash occurs is when player try to reach other dimension from space except overworld. It is the only case.

**Comment by mskorzhinskiy** [comment] 2019-08-29 09:25
A bunch of theories\questions. Not sure if this is helpful, I even do not have any real Java experience. You can safely ignore my rambling.

1) Chunk is already loaded?

You mentioned that NPE happens on access attempt to multimap instance passed to putAll function. Could it be that "forcedChunks.get(ticket.world)" returned nothing? Do I understand that code right?

If so, could it be that some chunks are already loaded \ impossible to load? May be calling this function on such chunks is prohibited?

2) Some callback inside of warddrive called during chunkForce?

Does this line of code calls something inside of warpdrive code, like some kind of callback? Is it executed immediatly?

`  MinecraftForge.EVENT_BUS.post(new ForceChunkEvent(ticket, chunk));`

May be something happens there?

3) Logs before the crash suggestes that world that causing crash is unloaded during the jumping process. Is it right?

I cut a lot from logs to show what I am talking about:

> [22:30:47] #6 Getting initial target vector...
> [22:30:47] Loading dimension 1 (New World)  **<<< dimension 1 is 'The End'**
> [22:30:48] #6 From world solarSystem to DIM1
> [22:30:48] Unloading dimension 1            **<<< why?** 
> [22:30:48] #7 Adjusting jump vector...
> [22:30:48] #8 Loading chunks at target...
> [22:30:48] #8 Forcing target chunks in DIM1 **<<< Crash!**

I've seen a suggestion from one of the thread about similiar bug in other mod that it looks like the world is not loaded at the moment and this is causing crash. No elaboration was done there, just a suggestion, so not attaching a link.

**Comment by LemADEC** [comment] 2019-08-29 20:03
You can have overlapping chunkloaders covering the same chunks.
There's no ForceChunkEvent handler in WarpDrive.

The issue is more that the world isn't loaded yet, was unloaded or was reloaded.
There's a forge option to avoid that kind of issue, it's named `dimensionUnloadQueueDelay`. Sadly, it defaults to 0 which might explain the instant unloading seen here. It should be at least 100 (5 seconds) or even 6000 (5 mn measured in ticks).

Short term, you could just change this value.
Long term, I'll add a ticket earlier in the sequencer so Forge doesn't unload too fast.

**Comment by mskorzhinskiy** [comment] 2019-08-30 08:03
> Short term, you could just change this value.

Yes, it works. Tried some jumping with pluto\customly created worlds and everthing works correctly.

Thank you for your time and effort.

**Closed as completed** 2019-09-16 19:59 UTC
Labels: Pending user feedback
