### ISSUE TITLE
Advanced solar Panels mod - Crash on jump

### ISSUE THREAD

**Issue by StargateMC** [LemADEC/WarpDrive#206] opened 2016-08-31 22:20 UTC
Hi Lemadec - we just updated to the latest release built (.26).
The advanced solars crashes are happening again, see the crash report on here: https://github.com/StargateMC/StargateMCPublic/issues/174

Pastebin of server log : http://pastebin.com/j07MhAWs

**Comment by LemADEC** [comment] 2016-08-31 23:40
I can't reproduce this on the official server using Thermos 1.7.10-1614.57.

I see a crash report during the jump that is involving a MassiveLag plugin, IC2 EnergyNet and a Prism plugin:

```
[15:15:51] [Server thread/ERROR] [FML/]: Exception caught during firing event ic2.api.energy.event.EnergyTileLoadEvent@76dc89fa:
java.lang.NullPointerException
        at ic2.core.energy.EnergyNetLocal.addTileToGrids(EnergyNetLocal.java:627) ~[EnergyNetLocal.class:?]
        at ic2.core.energy.EnergyNetLocal.addTileEntity(EnergyNetLocal.java:185) ~[EnergyNetLocal.class:?]
        at ic2.core.energy.EnergyNetLocal.addTileEntity(EnergyNetLocal.java:66) ~[EnergyNetLocal.class:?]
        at ic2.core.energy.EventHandler.onEnergyTileLoad(EventHandler.java:28) ~[EventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_43_EventHandler_onEnergyTileLoad_EnergyTileLoadEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1614.58]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:1.7.10-1614.58]
        at advsolar.common.tiles.TileEntitySolarPanel.onLoaded(TileEntitySolarPanel.java:112) [TileEntitySolarPanel.class:?]
        at advsolar.common.tiles.TileEntitySolarPanel.func_145829_t(TileEntitySolarPanel.java:91) [TileEntitySolarPanel.class:?]
        at net.minecraft.world.chunk.Chunk.func_150812_a(Chunk.java:1007) [apx.class:?]
        at net.minecraft.world.World.func_147455_a(World.java:3271) [ahb.class:?]
        at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:958) [apx.class:?]
        at net.minecraft.world.World.func_147438_o(World.java:3211) [ahb.class:?]
        at org.bukkit.craftbukkit.v1_7_R4.block.CraftBlock.getState(CraftBlock.java:307) [CraftBlock.class:1.7.10-1614.58]
        at me.botsko.prism.listeners.PrismBlockPhysicsEvent.onBlockPhysics(PrismBlockPhysicsEvent.java:61) [prism.jar:?]
        at sun.reflect.GeneratedMethodAccessor89.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
        at com.massivecraft.massivelag.inject.event.MassiveLagEventExecutor.execute(MassiveLagEventExecutor.java:67) [MassiveLag.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [RegisteredListener.class:1.7.10-1614.58]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.58]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.58]
        at net.minecraft.world.World.func_147460_e(World.java:1139) [ahb.class:?]
        at ic2.core.energy.EnergyNetLocal.addTileEntity(EnergyNetLocal.java:181) [EnergyNetLocal.class:?]
        at ic2.core.energy.EnergyNetLocal.addTileEntity(EnergyNetLocal.java:66) [EnergyNetLocal.class:?]
        at ic2.core.energy.EventHandler.onEnergyTileLoad(EventHandler.java:28) [EventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_43_EventHandler_onEnergyTileLoad_EnergyTileLoadEvent.invoke(.dynamic) [?:1.7.10-1614.58]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:1.7.10-1614.58]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:1.7.10-1614.58]
        at ic2.core.block.wiring.TileEntityCable.onLoaded(TileEntityCable.java:159) [TileEntityCable.class:?]
        at ic2.core.block.TileEntityBlock$1.tickCallback(TileEntityBlock.java:60) [TileEntityBlock$1.class:?]
        at ic2.core.TickHandler.processTickCallbacks(TickHandler.java:175) [TickHandler.class:?]
        at ic2.core.TickHandler.onWorldTick(TickHandler.java:60) [TickHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_25_TickHandler_onWorldTick_WorldTickEvent.invoke(.dynamic) [?:1.7.10-1614.58]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) [ASMEventHandler.class:1.7.10-1614.58]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:1.7.10-1614.58]
        at cpw.mods.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:273) [FMLCommonHandler.class:1.7.10-1614.58]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:957) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

From what I've understood of that crash:
1- An IC2 cable loaded itself before ship transfer was done.
2- Loaded means adding itself to IC2 EnergyNet.
3- IC2 EnergyNet called notifyBlockOfNeighborChange(air).
4- MassiveLag got involved and interpreted it as a physics event, passing it to Prism (1).
5- Prism loaded the referenced block triggering a chunkloading event out of context (2).
6- Said block tried initializing itself with IC2 EnergyNet too soon.
7- IC2 EnergyNet fails to validate it's context and crashed.

4 doesn't make much sense => try to reproduce with and without plugins.
5 means the block was outside the ship boundaries or server fails to keep chunks loaded, either ways it's not a WarpDrive issue.
6 is a (known) bug in Advanced Solar Panel

Assuming it's a WarpDrive issue, I'll need to reproduce it first, which isn't the case here.

As for the player crashing the server, the crashlog provided is incomplete. Notably, I don't know if the faulty block is at original or final position. I suppose the map is corrupted at this location and requires some remote or offline modification.

**Comment by StargateMC** [comment] 2016-08-31 23:59
Hi @lemadec The plugins don't factor into this at all - they perform monitoring actions, with no chunk loads performed. 
The issue appears with or without plugins installed (as was the case last time)..

It doesn't happen all the time however as I did  6 same dimension and 4 cross dimension jumps successfully... 

As for the block location... This is not mentioned in the crash report but I'll grab the full one when I get home.

@robotia is there any weird stuff in the thermos builds after cauldron stopped development that would impact on this?

@lemadec what ic2 build do you use? Do you run any other ic2 integrating mods?

**Comment by LemADEC** [comment] 2016-09-01 00:28
the pack is public: http://www.technicpack.net/modpack/world-war-minecraft-9.874951/mods

**Comment by StargateMC** [comment] 2016-09-01 00:42
I am going to go over your configs with a fine tooth comb... Looks like we run same versions of everything....

Side note mine is too.. If you have time to review configs for idiot mistakes ;) http://www.technicpack.net/modpack/stargatemc.135186

**Comment by LemADEC** [comment] 2016-09-01 01:13
I see a few obsolete mods in there.
advancedmachines, DonsLightningRodMod, ProjectRed and GregsLighting are prime suspects.

**Comment by StargateMC** [comment] 2016-09-01 01:48
What do you mean obselete ?

None of these mods exist on the ship that died haha :(

**Comment by LemADEC** [comment] 2016-09-01 07:54
Some mods are not on there latest version.
I've listed mods that are untested or known to cause issues.

**Comment by StargateMC** [comment] 2016-09-03 01:31
@LemADEC Can confirm, none of those machines are onboard the WD ship that crashed our server. Really wishing IC2 was open source right about now....

**Comment by LemADEC** [comment] 2016-09-03 08:08
You don't need to have the block onboard for the mods to cause issue.

**Comment by LemADEC** [comment] 2016-09-29 01:05
Any updates on this?

**Comment by StargateMC** [comment] 2016-10-08 03:27
The issue still happens when I don't have them installed. I use multiworld (bukkit) for my world provider, the only thing I cant think of would be that.

**Comment by LemADEC** [comment] 2016-10-08 11:14
Multiworld is risky business, that's for sure.

**Comment by StargateMC** [comment] 2016-10-08 14:08
Lol, it works fine! Just no adv Solars 

Side note... generating a ship by command now causes the ship to load and then be invisible for a few minutes. Blocks are there you just can't see them lol.
Then bam, come back from a coffee and the ship is visible.
Not a lag issue - I have 32gb ram and 8 CPU cores on the server.

**Comment by StargateMC** [comment] 2016-10-08 14:09
(Dedicated server)

**Comment by LemADEC** [comment] 2016-10-08 14:31
I understand AdvancedSolars were the issue, so I'll be closing this ticket.

As for your ship not appearing, it can be a bandwidth issue or a plugin interfering which block updates. Does it appear immediately if you place or remove a block?

**Comment by StargateMC** [comment] 2016-10-17 20:52
Hi @LemADEC 
As of the most recent update for Mekanism (9.1) it is also doing the same thing with IC2 on occasion, see here: http://pastebin.com/rp7XzTxh

Not related to your issue, but similar outcome, the chunk being loaded crashes everything... maybe that would help with debugging.

Older versions of Mek didnt do this.

**Comment by LemADEC** [comment] 2016-10-17 23:13
That's a bug in Mekanism handling of chunkloading, no relation whatsoever.

**Closed as completed by LemADEC** 2016-10-17 23:13 UTC

**Comment by StargateMC** [comment] 2016-10-18 06:18
OK a mod that modifies the air tile entity is the culprit.... i think.

Both the AdvSolars WarpDrive issue and the Mekanism issue are causing server crashes when the ic2 'neighbour' tile is tile.Air (it shouldnt be a neighbour!). Nothing to do with chunk loads that I can see. Both crashes occur on the same line of code in IC2 as part of an EnergyTileLoadEvent.

Im trying to dig deeper (I understand you closed the issue), but do you think I might be on to something?

**Comment by LemADEC** [comment] 2016-10-18 09:34
tile.air is the vanilla air block.

You've 2 Mekanism issues here:
First, Mekanism checked for redstone power without checking for loaded chunk (technically, it's a vanilla inherited bug that mods need to handle manually).
Second, Mekanism registered to IC2 EnergyNetwork during the ChunkLoading event, something you should never do because TE aren't initialized yet at that time on 1.7.

**Comment by StargateMC** [comment] 2016-10-18 09:48
So without building a custom version of mek, a solution would be to load the chunk before the NPE if it isn't already?

**Comment by LemADEC** [comment] 2016-10-18 09:50
Use the old Mekanism until they fix their bug
Pay a dev to fix it for them
Remove IC2 support from Mekanism
etc.
