### ISSUE TITLE
1.3.1 requires IC2 due to loading ItemReactorLaserFocus

### ISSUE THREAD

**Issue by jonabrv1965** [LemADEC/WarpDrive#43] opened 2015-08-09 14:57 UTC
Here the crash report :+1: 
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 8/9/15 9:50 AM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: cr0s/warpdrive/item/ItemReactorLaserFocus
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: cr0s/warpdrive/item/ItemReactorLaserFocus
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:440)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: cr0s.warpdrive.item.ItemReactorLaserFocus
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 34 more
Caused by: java.lang.NoClassDefFoundError: ic2/api/reactor/IReactorComponent
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 36 more
Caused by: java.lang.ClassNotFoundException: ic2.api.reactor.IReactorComponent
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 40 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_45, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 775047048 bytes (739 MB) / 1904214016 bytes (1816 MB) up to 5726797824 bytes (5461 MB)
    JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1481 Optifine OptiFine_1.7.10_HD_U_C1 71 mods loaded, 71 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UC  mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UC  FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1481-1.7.10.jar) 
    UC  Forge{10.13.4.1481} [Minecraft Forge](forge-1.7.10-10.13.4.1481-1.7.10.jar) 
    UC  CodeChickenCore{1.0.7.46} [CodeChicken Core](minecraft.jar) 
    UC  Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) 
    UC  NotEnoughItems{1.0.5.110} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.110-universal.jar) 
    UC  OpenComputers|Core{1.5.15.31} [OpenComputers (Core)](minecraft.jar) 
    UC  backpacks16840{3.0.4} [Backpacks!](zz-backpacks 1.7.10 - 3.0.4.jar) 
    UC  BuildCraft|Core{7.0.20} [BuildCraft](buildcraft-7.0.20.jar) 
    UC  BuildCraft|Silicon{7.0.20} [BC Silicon](buildcraft-7.0.20.jar) 
    UC  BuildCraft|Transport{7.0.20} [BC Transport](buildcraft-7.0.20.jar) 
    UC  BuildCraft|Factory{7.0.20} [BC Factory](buildcraft-7.0.20.jar) 
    UC  additionalpipes{4.6.0} [Additional Pipes](additionalpipes-4.6.0.jar) 
    UC  asielib{0.4.2} [asielib](AsieLib-1.7.10-0.4.2.jar) 
    UC  bdlib{1.9.1.97} [BD Lib](bdlib-1.9.1.97-mc1.7.10.jar) 
    UC  BuildCraft|Builders{7.0.20} [BC Builders](buildcraft-7.0.20.jar) 
    UC  BuildCraft|Robotics{7.0.20} [BC Robotics](buildcraft-7.0.20.jar) 
    UC  BuildCraft|Energy{7.0.20} [BC Energy](buildcraft-7.0.20.jar) 
    UC  BuildCraft|Compat{7.0.11} [BuildCraft Compat](buildcraft-compat-7.0.11.jar) 
    UC  ChickenChunks{1.3.4.16} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.16-universal.jar) 
    UC  EnderStorage{1.4.7.36} [EnderStorage](EnderStorage-1.7.10-1.4.7.36-universal.jar) 
    UC  ForgeMultipart{1.2.0.345} [Forge Multipart](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UC  OpenComputers{1.5.15.31} [OpenComputers](OpenComputers-MC1.7.10-1.5.15.31-universal.jar) 
    UC  Railcraft{9.6.1.0} [Railcraft](Railcraft_1.7.10-9.6.1.0.jar) 
    UC  Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    UC  computronics{1.5.6} [Computronics](Computronics-1.7.10-1.5.6.jar) 
    UC  MiscUtils{@VERSION@} [MiscUtils](MiscUtils-universal-1.7.10-1.0.8.jar) 
    UC  Circuit{1.0.2} [DataCircuits](DataCircuits-universal-1.7.10-1.0.2.jar) 
    UC  OmnisCore{0.1.0} [Omnis Core](OmnisCore-1.7.10 - 0.0.6-universal.jar) 
    UC  dimensionalPockets{0.11.4.1} [Dimensional Pockets](DimensionalPockets-1.7.10-0.11.4.1-universal.jar) 
    UC  dirtydiamonds{1.2.7} [Dirty Diamonds](Dirty Diamonds v1.2.7 %281.7.10%29.jar) 
    UC  eplus{3.0.2-d} [Enchanting Plus](EnchantingPlus-1.7.10-3.0.2-d.jar) 
    UC  enhancedportals{3.0.12} [EnhancedPortals](EnhancedPortals_1.7.10-universal-3.0.12.jar) 
    UC  GalacticraftCore{3.0.12} [Galacticraft Core](GalacticraftCore-1.7-3.0.12.345.jar) 
    UC  GalacticraftMars{3.0.12} [Galacticraft Planets](Galacticraft-Planets-1.7-3.0.12.345.jar) 
    UC  advgenerators{0.9.17.102} [Advanced Generators](generators-0.9.17.102-mc1.7.10.jar) 
    UC  llor{1.0.2} [Light Level Overlay Reloaded](LLOverlayReloaded-1.0.2-mc1.7.10.jar) 
    UC  LogisticsPipes{0.9.2.30} [Logistics Pipes](logisticspipes-0.9.2.30.jar) 
    UC  LunatriusCore{1.1.2.21} [LunatriusCore](LunatriusCore-1.7.10-1.1.2.21-universal.jar) 
    UC  meteors{2.14.3} [Falling Meteors](meteors-1.7.10-2.14.3.jar) 
    UC  MorePlanet{1.2.9} [More Planets](More-Planets-1.7.10-1.2.9.jar) 
    UC  NEIAddons{1.12.10.33} [NEI Addons](neiaddons-1.12.10.33-mc1.7.10.jar) 
    UC  NEIAddons|AppEng{1.12.10.33} [NEI Addons: Applied Energistics 2](neiaddons-1.12.10.33-mc1.7.10.jar) 
    UC  NEIAddons|Botany{1.12.10.33} [NEI Addons: Botany](neiaddons-1.12.10.33-mc1.7.10.jar) 
    UC  NEIAddons|Forestry{1.12.10.33} [NEI Addons: Forestry](neiaddons-1.12.10.33-mc1.7.10.jar) 
    UC  NEIAddons|CraftingTables{1.12.10.33} [NEI Addons: Crafting Tables](neiaddons-1.12.10.33-mc1.7.10.jar) 
    UC  NEIAddons|ExNihilo{1.12.10.33} [NEI Addons: Ex Nihilo](neiaddons-1.12.10.33-mc1.7.10.jar) 
    UC  neiintegration{1.0.11} [NEI Integration](NEIIntegration-MC1.7.10-1.0.11.jar) 
    UC  ObsidianTools{1.0.0} [ObsidianTools](Obsidian Tools Mod.jar) 
    UC  opensecurity{1.0.59} [OpenSecurity](OpenSecurity-1.0-59.jar) 
    UC  pandorasbox{2.0.1} [Pandora's Box](PandorasBox-2.1.jar) 
    UC  PetBat{1.3.6} [Pet Bat](PetBat-1.7.10.jar) 
    UC  QuarryPlus{2.1.0} [QuarryPlus](QuarryPlus-1.7.10-2.1.0.jar) 
    UC  ripm{1.7.10-3.4} [ripm](Recycle Items Plus Mod-1.7.10-3.4.zip) 
    UC  AS_Ruins{15.0} [Ruins Spawning System](Ruins-1.7.10.jar) 
    UC  cientificalchemy{1.0} [cientificalchemy](ScientificAlchemy-1.7.10-1.3.jar) 
    UC  SlimevoidLib{2.0.4.7} [Slimevoid Library](SlimevoidLibrary-2.0.4.7.jar) 
    UC  StorageDrawers{1.7.10-1.5.12} [Storage Drawers](StorageDrawers-1.7.10-1.5.12.jar) 
    UC  thutcore{2.0} [ThutCore](thuttech-oc.jar) 
    UC  ThutTech{1.0.0} [Thut's Tech](thuttech-oc.jar) 
    UC  jordy141minecraftmagicwrench{0.5 Alpha} [Magic Wrench](UncraftingTable-1.7.10-alpha1.jar) 
    UC  uncraftingTable{1.7.10 Alpha 1} [Uncrafting Table](UncraftingTable-1.7.10-alpha1.jar) 
    UC  AS_UpdateCheck{1.1.6} [AtomicStryker Update Check Mod](UpdateCheckerMod-1.7.10.jar) 
    UC  utilityworlds{1.0.7} [Utility Worlds](UtilityWorlds-1.7.10_1.0.7.jar) 
    UE  WarpDrive{1.3.1} [WarpDrive](warpdrive-1.3.1.jar) 
    UC  WR-CBE|Core{1.4.1.9} [WR-CBE Core](WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    UC  WR-CBE|Addons{1.4.1.9} [WR-CBE Addons](WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    UC  WR-CBE|Logic{1.4.1.9} [WR-CBE Logic](WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    UC  zyinhud{1.3.9} [Zyin's HUD](ZyinsHUD-%281.7.10%29-v.1.3.9.jar) 
    UC  McMultipart{1.2.0.345} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UC  ForgeMicroblock{1.2.0.345} [Forge Microblocks](ForgeMultipart-1.7.10-1.2.0.345-universal.jar)

**Comment by LemADEC** [comment] 2015-08-10 00:01
Looks like an IC2 dependency derp.

**Comment by LemADEC** [comment] 2015-08-10 10:32
I can't reproduce it with just WarpDrive. IC2 recipes were fixed in 1.3.2, try it out.

**Closed as completed** 2015-08-10 10:32 UTC
Labels: high Priority
